export const APPS = Object.freeze([
  { url: "grades.html", name: "Grades", icon: "🎓", group: "grp.school", locked: true,
    keywords: ["noten", "points", "moyenne", "average", "zensuren"] },
  { url: "timetable.html", name: "Stonneplang", icon: "🗓️", group: "grp.school", locked: true,
    keywords: ["stonneplang", "stundenplan", "horaire", "schedule"] },
  { url: "exams.html", name: "Tester", icon: "⏳", group: "grp.school", locked: true,
    keywords: ["prüfungen", "examens", "tests", "countdown", "notizen"] },
  { url: "homework.html", name: "Hausaufgaben", icon: "📚", group: "grp.school", locked: false,
    keywords: ["homework", "devoirs", "aufgaben", "webuntis"] },
  { url: "flashcards.html", name: "Kaarten", icon: "🃏", group: "grp.school", locked: true,
    keywords: ["flashcards", "karteikarten", "cartes", "lernen", "réviser"] },
  { url: "board.html", name: "Klass-Tafel", icon: "📋", group: "grp.school", locked: true,
    keywords: ["class board", "tafel", "tableau", "hausaufgaben", "devoirs"] },
  { url: "ask.html", name: "Frot deng Daten", icon: "🧠", group: "grp.school", locked: true,
    keywords: ["ai", "daten", "données", "fragen", "questions"] },
  { url: "search.html", name: "Sichen", icon: "🔎", group: "grp.school", locked: true,
    keywords: ["search", "suchen", "recherche", "finden", "trouver"] },
  { url: "countries.html", name: "Länner-Verglach", icon: "🌍", group: "grp.school", locked: false,
    keywords: ["länder", "countries", "pays", "vergleich", "comparison", "bevölkerung",
               "population", "bip", "gdp", "hauptstadt", "capitale", "geografie"] },

  { url: "messenger.html", name: "Messenger", icon: "💬", group: "grp.social", locked: true,
    keywords: ["chat", "noriichten", "nachrichten", "messages", "gruppen"] },
  { url: "inbox.html", name: "Vereenegt Inbox", icon: "📥", group: "grp.social", locked: true,
    keywords: ["inbox", "noriichten", "messagen", "nachrichten", "messages", "whatsapp", "imessage", "mail", "email", "e-mail", "boîte de réception"] },
  { url: "friends.html", name: "Friends", icon: "👥", group: "grp.social", locked: true,
    keywords: ["frënn", "freunde", "amis", "contacts"] },
  { url: "classchat.html", name: "Klass-Chat", icon: "🗣️", group: "grp.social", locked: true,
    keywords: ["classe", "klassenchat", "classroom", "chat"] },
  { url: "polls.html", name: "Ëmfroen", icon: "🗳️", group: "grp.social", locked: false,
    keywords: ["umfragen", "sondages", "polls", "vote", "stëmmen"] },
  { url: "alerts.html", name: "Neiegkeeten", icon: "🔔", group: "grp.social", locked: true,
    keywords: ["notifications", "benachrichtigungen", "mentions", "alertes"] },
  { url: "profile.html", name: "Profile", icon: "🪪", group: "grp.social", locked: true,
    keywords: ["profil", "account", "konto", "avatar", "stats"] },

  { url: "pixelbreak.html", name: "PixelBreak", icon: "🎮", group: "grp.fun", locked: false,
    keywords: ["arcade", "spiller", "spiele", "games", "2 ipad"] },
  { url: "partyspill.html", name: "Partyspill", icon: "🎉", group: "grp.fun", locked: false,
    keywords: ["partyspiele", "jeux", "fête", "gruppen", "handy"] },
  { url: "wordle.html", name: "Wuertspill", icon: "🟩", group: "grp.fun", locked: false,
    keywords: ["wordle", "wörter", "wierder", "mots", "guess"] },
  { url: "countdowns.html", name: "Countdowns", icon: "⏳", group: "grp.fun", locked: false,
    keywords: ["timer", "zäit", "zeit", "compte à rebours", "dates"] },

  { url: "bus.html", name: "Bus & Zuch", icon: "🚌", group: "grp.maps", locked: false,
    keywords: ["train", "zuch", "tram", "departures", "horaire", "fahrplan"] },
  { url: "moien.html", name: "Moien", icon: "🌤️", group: "grp.maps", locked: false,
    keywords: ["weather", "wieder", "météo", "forecast", "prévisions"] },
  { url: "skylens.html", name: "SkyLens", icon: "🛩️", group: "grp.maps", locked: false,
    keywords: ["flights", "fliger", "flugzeuge", "avions", "radar"] },
  { url: "kaart/", name: "Wanderkaart", icon: "🗺️", group: "grp.maps", locked: false,
    keywords: ["map", "karte", "carte", "wandern", "randonnée", "mtb"] },
  { url: "geoportal/", name: "Geoportal", icon: "🛰️", group: "grp.maps", locked: false,
    keywords: ["maps", "karten", "cartes", "kadaster", "luftbilder", "cadastre"] },

  { url: "buddy.html", name: "Study Buddy", icon: "🤖", group: "grp.personal", locked: true,
    keywords: ["study", "lernen", "léieren", "devoirs", "homework", "ai"] },
  { url: "health.html", name: "Health", icon: "💪", group: "grp.personal", locked: true,
    keywords: ["gesundheit", "santé", "gesondheet", "water", "schlaf", "sport"] },
  { url: "money.html", name: "Sue", icon: "💶", group: "grp.personal", locked: true,
    keywords: ["geld", "argent", "suen", "ausgaben", "dépenses", "subscriptions"] },
  { url: "me.html", name: "My Dashboard", icon: "📊", group: "grp.personal", locked: false,
    keywords: ["stats", "traffic", "github", "analytics", "statistiken"] },
  { url: "karts.html", name: "KartTracker", icon: "🏎️", group: "grp.personal", locked: false,
    keywords: ["karting", "ronnen", "runden", "tours", "laps", "zeiten"] },
  { url: "hotel.html", name: "Hotel-Simulator", icon: "🏨", group: "grp.personal", locked: false,
    keywords: ["builder", "bauen", "simulateur", "building", "hotel"] },
  { url: "haus/", name: "Haus-Planer", icon: "🏠", group: "grp.personal", locked: true,
    keywords: ["haus", "house", "bauen", "builder", "grundriss", "floor plan"] },

  { url: "factory.html", name: "Dashboard", icon: "📈", group: "grp.private", locked: false,
    keywords: ["shorts", "shortsfactory", "analytics", "video", "stats"] },
  { url: "admin.html", name: "Admin", icon: "🛡", group: "grp.private", locked: false,
    keywords: ["moderation", "verwaltung", "manage", "users", "benotzer"] },
  { url: "ppt.html", name: "PPT Builder", icon: "▣", group: "grp.private", locked: false,
    keywords: ["powerpoint", "presentation", "présentation", "slides", "folien"] },
  { url: "doc.html", name: "Word Builder", icon: "📄", group: "grp.private", locked: false,
    keywords: ["word", "dokument", "document", "texte", "writer"] },
]);
