/* Quiz-board question banks. Pure data, no logic.
 *
 * Shape: 3 banks, each 5 categories x 5 clues, values 100..500.
 * Every string is {lb, de, en}, Luxembourgish first.
 *
 * Written from scratch for ian.lu. Facts kept to stable, checkable ones
 * (geography, history, biology) rather than anything that dates quickly.
 */
window.JQ_BANKS = [
{
  id: "scouten",
  name: { lb: "Scouten", de: "Pfadfinder", en: "Scouting" },
  cats: [
    { name: { lb: "Knäppchen", de: "Knoten", en: "Knots" }, clues: [
      { q: { lb: "Wéi ee Knäppche benotzt du fir zwee glech décke Seeler ze verbannen?", de: "Welchen Knoten nutzt du, um zwei gleich dicke Seile zu verbinden?", en: "Which knot joins two ropes of equal thickness?" },
        a: { lb: "De Kreuzknäppchen", de: "Der Kreuzknoten", en: "The reef knot" } },
      { q: { lb: "Wéi ee Knäppche mécht eng Bucht déi sech net zesummenzitt?", de: "Welcher Knoten macht eine Schlinge, die sich nicht zuzieht?", en: "Which knot makes a loop that will not tighten?" },
        a: { lb: "De Palstek", de: "Der Palstek", en: "The bowline" } },
      { q: { lb: "Wéi ee Knäppche benotzt de Kletterer als Sécherung um Enn vum Seel?", de: "Welchen Knoten nutzen Kletterer als Sicherung am Seilende?", en: "Which knot do climbers tie as a stopper at the rope's end?" },
        a: { lb: "Den Aachterknäppchen", de: "Der Achterknoten", en: "The figure-eight knot" } },
      { q: { lb: "Wéi verbënnt een zwee Stécker Holz am rechten Wénkel beim Bauen?", de: "Wie verbindet man zwei Hölzer im rechten Winkel beim Bauen?", en: "How do you lash two poles together at a right angle?" },
        a: { lb: "Mat enger Kreuzbindung", de: "Mit einem Kreuzbund", en: "With a square lashing" } },
      { q: { lb: "Wéi ee Knäppche léisst sech nach ënner Spannung liicht opmaachen?", de: "Welcher Knoten lässt sich noch unter Spannung leicht öffnen?", en: "Which knot can still be released easily under load?" },
        a: { lb: "De Zimmermannsstek", de: "Der Zimmermannsstek", en: "The timber hitch" } },
    ]},
    { name: { lb: "Camp", de: "Lager", en: "Camp" }, clues: [
      { q: { lb: "Firwat gräift man e Zelt ni un d'Bannenzelt wann et reent?", de: "Warum berührt man bei Regen nie das Innenzelt?", en: "Why should you never touch the inner tent when it rains?" },
        a: { lb: "Well d'Waasser dann duerchzitt", de: "Weil das Wasser dann durchzieht", en: "Because water then wicks through" } },
      { q: { lb: "Wat leet man ënnert de Schlofsak fir waarm ze bleiwen?", de: "Was legt man unter den Schlafsack, um warm zu bleiben?", en: "What goes under your sleeping bag to keep you warm?" },
        a: { lb: "Eng Isomatte", de: "Eine Isomatte", en: "A sleeping mat" } },
      { q: { lb: "Wéi eng Form gëtt e Feier dat séier vill Hëtzt gëtt?", de: "Welche Form gibt ein Feuer, das schnell viel Hitze gibt?", en: "Which fire shape gives a lot of heat quickly?" },
        a: { lb: "E Pyramiden- oder Tipi-Feier", de: "Ein Pyramiden- oder Tipi-Feuer", en: "A teepee fire" } },
      { q: { lb: "Wat muss ëmmer bei engem Lagerfeier stoen?", de: "Was muss bei einem Lagerfeuer immer bereitstehen?", en: "What must always be next to a campfire?" },
        a: { lb: "Waasser oder Sand fir ze lëschten", de: "Wasser oder Sand zum Löschen", en: "Water or sand to put it out" } },
      { q: { lb: "Firwat baut man en Zelt net an enger Mulde op?", de: "Warum baut man ein Zelt nicht in einer Mulde auf?", en: "Why not pitch a tent in a hollow?" },
        a: { lb: "Do sammelt sech d'Waasser", de: "Dort sammelt sich das Wasser", en: "Water collects there" } },
    ]},
    { name: { lb: "Éischt Hëllef", de: "Erste Hilfe", en: "First aid" }, clues: [
      { q: { lb: "Wéi eng Notrufnummer gëllt an der ganzer EU?", de: "Welche Notrufnummer gilt in der ganzen EU?", en: "Which emergency number works across the EU?" },
        a: { lb: "112", de: "112", en: "112" } },
      { q: { lb: "Wéi laang killt man eng Verbrennung mat Waasser?", de: "Wie lange kühlt man eine Verbrennung mit Wasser?", en: "How long do you cool a burn with water?" },
        a: { lb: "E puer Minutten, mat lauwaarmem Waasser", de: "Mehrere Minuten, mit lauwarmem Wasser", en: "Several minutes, with lukewarm water" } },
      { q: { lb: "A wéi eng Positioun leet man een deen ouni Bewosstsinn ass awer otemt?", de: "In welche Lage bringt man eine bewusstlose Person, die atmet?", en: "What position for someone unconscious but breathing?" },
        a: { lb: "Stabil Säitelag", de: "Stabile Seitenlage", en: "The recovery position" } },
      { q: { lb: "Wat kontrolléiert man als éischt bei engem Onfall?", de: "Was prüft man bei einem Unfall zuerst?", en: "What do you check first at an accident?" },
        a: { lb: "Ob et fir dech selwer sécher ass", de: "Ob es für dich selbst sicher ist", en: "Whether the scene is safe for you" } },
      { q: { lb: "Wat mécht man bei staarkem Bluten un engem Aarm?", de: "Was tut man bei starker Blutung am Arm?", en: "What do you do for heavy bleeding on an arm?" },
        a: { lb: "Drock drop an den Aarm héich halen", de: "Druck darauf und den Arm hochhalten", en: "Apply pressure and raise the arm" } },
    ]},
    { name: { lb: "Orientéierung", de: "Orientierung", en: "Navigation" }, clues: [
      { q: { lb: "Op wéi eng Säit weist d'Nol vum Kompass?", de: "Wohin zeigt die Kompassnadel?", en: "Which way does a compass needle point?" },
        a: { lb: "Op den Norden", de: "Nach Norden", en: "North" } },
      { q: { lb: "Wéi vill Grad huet eng ganz Kompassrous?", de: "Wie viele Grad hat eine ganze Kompassrose?", en: "How many degrees in a full compass rose?" },
        a: { lb: "360", de: "360", en: "360" } },
      { q: { lb: "Wéi eng Linnen op enger Kaart verbannen Punkten mat der selwechter Héicht?", de: "Welche Linien auf einer Karte verbinden Punkte gleicher Höhe?", en: "Which lines on a map join points of equal height?" },
        a: { lb: "Héichtelinnen", de: "Höhenlinien", en: "Contour lines" } },
      { q: { lb: "Wou steet d'Sonn ongeféier um Mëtteg?", de: "Wo steht die Sonne mittags etwa?", en: "Roughly where is the sun at midday?" },
        a: { lb: "Am Süden", de: "Im Süden", en: "In the south" } },
      { q: { lb: "Wat heescht et wann op der Kaart 1:25 000 steet?", de: "Was bedeutet der Maßstab 1:25 000?", en: "What does a 1:25,000 scale mean?" },
        a: { lb: "1 cm op der Kaart ass 250 m an der Natur", de: "1 cm auf der Karte sind 250 m in der Natur", en: "1 cm on the map is 250 m on the ground" } },
    ]},
    { name: { lb: "Geschicht", de: "Geschichte", en: "History" }, clues: [
      { q: { lb: "Wien huet d'Scoutsbewegung gegrënnt?", de: "Wer gründete die Pfadfinderbewegung?", en: "Who founded the Scout movement?" },
        a: { lb: "De Robert Baden-Powell", de: "Robert Baden-Powell", en: "Robert Baden-Powell" } },
      { q: { lb: "A wéi ee Joerhonnert ass d'Scoutsbewegung entstanen?", de: "In welchem Jahrhundert entstand die Pfadfinderbewegung?", en: "In which century did Scouting begin?" },
        a: { lb: "Am 20. Joerhonnert (1907)", de: "Im 20. Jahrhundert (1907)", en: "The 20th century (1907)" } },
      { q: { lb: "Wéi ee Symbol ass d'weltweit Zeeche vun de Scouten?", de: "Welches Symbol ist das weltweite Pfadfinderzeichen?", en: "What is the worldwide Scout emblem?" },
        a: { lb: "D'Lilie (Fleur-de-lis)", de: "Die Lilie (Fleur-de-lis)", en: "The fleur-de-lis" } },
      { q: { lb: "Wat ass de Wahlspruch vun de Scouten?", de: "Was ist der Wahlspruch der Pfadfinder?", en: "What is the Scout motto?" },
        a: { lb: "Sief prett", de: "Sei bereit", en: "Be prepared" } },
      { q: { lb: "Wéi heescht e groussen internationale Scoutslager?", de: "Wie heißt ein großes internationales Pfadfinderlager?", en: "What is a large international Scout camp called?" },
        a: { lb: "E Jamboree", de: "Ein Jamboree", en: "A Jamboree" } },
    ]},
  ],
},
{
  id: "letzebuerg",
  name: { lb: "Lëtzebuerg", de: "Luxemburg", en: "Luxembourg" },
  cats: [
    { name: { lb: "Geographie", de: "Geografie", en: "Geography" }, clues: [
      { q: { lb: "Wéi vill Länner grenzen u Lëtzebuerg?", de: "Wie viele Länder grenzen an Luxemburg?", en: "How many countries border Luxembourg?" },
        a: { lb: "Dräi", de: "Drei", en: "Three" } },
      { q: { lb: "Wéi heescht de längsten Floss vu Lëtzebuerg?", de: "Wie heißt der längste Fluss Luxemburgs?", en: "What is Luxembourg's longest river?" },
        a: { lb: "D'Sauer", de: "Die Sauer", en: "The Sûre" } },
      { q: { lb: "Un wéi engem Floss gëtt de Wäin ugebaut?", de: "An welchem Fluss wird der Wein angebaut?", en: "Along which river are the vineyards?" },
        a: { lb: "Un der Musel", de: "An der Mosel", en: "The Moselle" } },
      { q: { lb: "Wéi vill Kantonen huet Lëtzebuerg?", de: "Wie viele Kantone hat Luxemburg?", en: "How many cantons does Luxembourg have?" },
        a: { lb: "Zwielef", de: "Zwölf", en: "Twelve" } },
      { q: { lb: "Wéi heescht de héchste Punkt vu Lëtzebuerg?", de: "Wie heißt der höchste Punkt Luxemburgs?", en: "What is Luxembourg's highest point?" },
        a: { lb: "De Kneiff", de: "Der Kneiff", en: "The Kneiff" } },
    ]},
    { name: { lb: "Geschicht", de: "Geschichte", en: "History" }, clues: [
      { q: { lb: "Wéi eng Regierungsform huet Lëtzebuerg?", de: "Welche Staatsform hat Luxemburg?", en: "What form of state is Luxembourg?" },
        a: { lb: "E Groussherzogtum", de: "Ein Großherzogtum", en: "A Grand Duchy" } },
      { q: { lb: "Wéi eng Sprooch ass zënter 1984 Nationalsprooch?", de: "Welche Sprache ist seit 1984 Nationalsprache?", en: "Which language became the national language in 1984?" },
        a: { lb: "Lëtzebuergesch", de: "Luxemburgisch", en: "Luxembourgish" } },
      { q: { lb: "Wéi eng dräi Sprooche sinn offiziell?", de: "Welche drei Sprachen sind offiziell?", en: "Which three languages are official?" },
        a: { lb: "Lëtzebuergesch, Franséisch, Däitsch", de: "Luxemburgisch, Französisch, Deutsch", en: "Luxembourgish, French, German" } },
      { q: { lb: "Wéi eng Sagefigur soll ënner dem Bockfiels wunnen?", de: "Welche Sagenfigur soll unter dem Bockfelsen wohnen?", en: "Which legendary figure is said to live under the Bock?" },
        a: { lb: "D'Melusina", de: "Melusina", en: "Melusina" } },
      { q: { lb: "Wéi heescht déi bekannteste Buerg am Norde vum Land?", de: "Wie heißt die bekannteste Burg im Norden?", en: "What is the best-known castle in the north?" },
        a: { lb: "D'Buerg Veianen", de: "Die Burg Vianden", en: "Vianden Castle" } },
    ]},
    { name: { lb: "Traditiounen", de: "Traditionen", en: "Traditions" }, clues: [
      { q: { lb: "Wéini ass Nationalfeierdag?", de: "Wann ist Nationalfeiertag?", en: "When is National Day?" },
        a: { lb: "Den 23. Juni", de: "Am 23. Juni", en: "23 June" } },
      { q: { lb: "Wéi heescht déi grouss Kiermes an der Stad am Hierscht?", de: "Wie heißt die große Kirmes in der Stadt?", en: "What is the city's big funfair called?" },
        a: { lb: "D'Schueberfouer", de: "Die Schueberfouer", en: "The Schueberfouer" } },
      { q: { lb: "A wéi enger Stad ass d'Sprangprozessioun?", de: "In welcher Stadt ist die Springprozession?", en: "Which town holds the hopping procession?" },
        a: { lb: "Echternach", de: "Echternach", en: "Echternach" } },
      { q: { lb: "Wat gëtt op Liichtmëss vun de Kanner gemaach?", de: "Was machen Kinder an Liichtmëss?", en: "What do children do at Liichtmëss?" },
        a: { lb: "Si ginn mat Lanterne sangen", de: "Sie ziehen mit Laternen singend umher", en: "They go singing with lanterns" } },
      { q: { lb: "Wéi heescht déi traditionell Wurscht op der Fouer?", de: "Wie heißt die traditionelle Wurst auf der Fouer?", en: "What is the traditional sausage at the fair?" },
        a: { lb: "D'Grillwurscht — a Gromperekichelcher dozou", de: "Die Grillwurst — mit Kartoffelpuffer", en: "Grilled sausage — with potato fritters" } },
    ]},
    { name: { lb: "Symbolen", de: "Symbole", en: "Symbols" }, clues: [
      { q: { lb: "Wéi eng dräi Faarwen huet d'Fändel?", de: "Welche drei Farben hat die Flagge?", en: "Which three colours are on the flag?" },
        a: { lb: "Rout, wäiss, blo", de: "Rot, weiß, blau", en: "Red, white, blue" } },
      { q: { lb: "Wéi eng Déier ass am Wope vu Lëtzebuerg?", de: "Welches Tier ist im Wappen Luxemburgs?", en: "Which animal is on Luxembourg's coat of arms?" },
        a: { lb: "E Léiw", de: "Ein Löwe", en: "A lion" } },
      { q: { lb: "Wéi heescht d'Nationalhymn?", de: "Wie heißt die Nationalhymne?", en: "What is the national anthem called?" },
        a: { lb: "Ons Heemecht", de: "Ons Heemecht", en: "Ons Heemecht" } },
      { q: { lb: "Wéi heescht de Stadtquartier mat den EU-Institutiounen?", de: "Wie heißt das Viertel mit den EU-Institutionen?", en: "Which quarter holds the EU institutions?" },
        a: { lb: "De Kirchbierg", de: "Der Kirchberg", en: "Kirchberg" } },
      { q: { lb: "Wéi heescht déi bekannte Bréck iwwer d'Pétrusse?", de: "Wie heißt die bekannte Brücke über die Petruss?", en: "What is the famous bridge over the Pétrusse?" },
        a: { lb: "D'Adolphe-Bréck", de: "Die Adolphe-Brücke", en: "The Adolphe Bridge" } },
    ]},
    { name: { lb: "Haut", de: "Heute", en: "Today" }, clues: [
      { q: { lb: "Wat ass zënter 2020 gratis fir jiddereen am Land?", de: "Was ist seit 2020 für alle im Land gratis?", en: "What has been free for everyone since 2020?" },
        a: { lb: "Den ëffentlechen Transport", de: "Der öffentliche Verkehr", en: "Public transport" } },
      { q: { lb: "Ongeféier wéi vill Leit wunnen zu Lëtzebuerg?", de: "Wie viele Menschen leben etwa in Luxemburg?", en: "Roughly how many people live in Luxembourg?" },
        a: { lb: "Ronn 670 000", de: "Rund 670 000", en: "About 670,000" } },
      { q: { lb: "Wéi heescht d'Regioun mat de Fielsen am Osten?", de: "Wie heißt die Felsenregion im Osten?", en: "What is the rocky region in the east called?" },
        a: { lb: "D'Mullerthal", de: "Das Müllerthal", en: "The Mullerthal" } },
      { q: { lb: "Wéi heesse déi markéierte Rondwanderweeër am Land?", de: "Wie heißen die markierten Rundwanderwege?", en: "What are the marked circular walks called?" },
        a: { lb: "Auto-Pédestres", de: "Auto-Pédestres", en: "Auto-Pédestres" } },
      { q: { lb: "Wéi eng Regioun heescht och d'Rout Erd?", de: "Welche Region heißt auch Rote Erde?", en: "Which region is also called the Red Rocks?" },
        a: { lb: "De Minett", de: "Der Minett", en: "The Minett" } },
    ]},
  ],
},
{
  id: "natur",
  name: { lb: "Natur & Wëssen", de: "Natur & Wissen", en: "Nature & Science" },
  cats: [
    { name: { lb: "Déieren", de: "Tiere", en: "Animals" }, clues: [
      { q: { lb: "Wéi vill Been huet eng Spann?", de: "Wie viele Beine hat eine Spinne?", en: "How many legs does a spider have?" },
        a: { lb: "Aacht", de: "Acht", en: "Eight" } },
      { q: { lb: "Wéi vill Been huet en Insekt?", de: "Wie viele Beine hat ein Insekt?", en: "How many legs does an insect have?" },
        a: { lb: "Sechs", de: "Sechs", en: "Six" } },
      { q: { lb: "Wat ass dat gréisst Déier op der Welt?", de: "Was ist das größte Tier der Welt?", en: "What is the largest animal on Earth?" },
        a: { lb: "De Bloswal", de: "Der Blauwal", en: "The blue whale" } },
      { q: { lb: "Wéi eng Insekten maachen Hunneg?", de: "Welche Insekten machen Honig?", en: "Which insects make honey?" },
        a: { lb: "D'Bienen", de: "Die Bienen", en: "Bees" } },
      { q: { lb: "Wat ass dat séierste Landdéier?", de: "Was ist das schnellste Landtier?", en: "What is the fastest land animal?" },
        a: { lb: "De Cheetah", de: "Der Gepard", en: "The cheetah" } },
    ]},
    { name: { lb: "Planzen", de: "Pflanzen", en: "Plants" }, clues: [
      { q: { lb: "Wéi heescht de Prozess mat deem Planzen aus Liicht Energie maachen?", de: "Wie heißt der Prozess, mit dem Pflanzen aus Licht Energie machen?", en: "What is the process by which plants make energy from light?" },
        a: { lb: "Photosynthese", de: "Photosynthese", en: "Photosynthesis" } },
      { q: { lb: "Wéi ee Gas gi Planzen dobäi of?", de: "Welches Gas geben Pflanzen dabei ab?", en: "Which gas do plants give off doing it?" },
        a: { lb: "Sauerstoff", de: "Sauerstoff", en: "Oxygen" } },
      { q: { lb: "Wéi ee Bam huet Eechelen?", de: "Welcher Baum hat Eicheln?", en: "Which tree has acorns?" },
        a: { lb: "D'Eech", de: "Die Eiche", en: "The oak" } },
      { q: { lb: "Wéi eng Deeler vun der Planz huelen d'Waasser op?", de: "Welche Teile der Pflanze nehmen Wasser auf?", en: "Which part of a plant takes up water?" },
        a: { lb: "D'Wuerzelen", de: "Die Wurzeln", en: "The roots" } },
      { q: { lb: "Wéi kann een d'Alter vun engem gefällten Bam zielen?", de: "Wie zählt man das Alter eines gefällten Baums?", en: "How do you tell a felled tree's age?" },
        a: { lb: "Un de Joresréng", de: "An den Jahresringen", en: "By its growth rings" } },
    ]},
    { name: { lb: "Weltraum", de: "Weltraum", en: "Space" }, clues: [
      { q: { lb: "Wéi vill Planéiten huet eist Sonnesystem?", de: "Wie viele Planeten hat unser Sonnensystem?", en: "How many planets are in our solar system?" },
        a: { lb: "Aacht", de: "Acht", en: "Eight" } },
      { q: { lb: "Wéi ee Planéit gëtt de roude Planéit genannt?", de: "Welcher Planet heißt der rote Planet?", en: "Which planet is called the red planet?" },
        a: { lb: "De Mars", de: "Der Mars", en: "Mars" } },
      { q: { lb: "Wat ass déi Sonn eigentlech?", de: "Was ist die Sonne eigentlich?", en: "What is the Sun, really?" },
        a: { lb: "E Stär", de: "Ein Stern", en: "A star" } },
      { q: { lb: "Wéi ee Planéit ass de gréissten?", de: "Welcher Planet ist der größte?", en: "Which planet is the largest?" },
        a: { lb: "De Jupiter", de: "Der Jupiter", en: "Jupiter" } },
      { q: { lb: "Ronn wéi vill Deeg brauch de Mound ëm d'Äerd?", de: "Wie viele Tage braucht der Mond um die Erde?", en: "Roughly how many days does the Moon take to orbit Earth?" },
        a: { lb: "Ronn 27 Deeg", de: "Rund 27 Tage", en: "About 27 days" } },
    ]},
    { name: { lb: "Kierper", de: "Körper", en: "Body" }, clues: [
      { q: { lb: "Wéi vill Kummeren huet d'Häerz?", de: "Wie viele Kammern hat das Herz?", en: "How many chambers does the heart have?" },
        a: { lb: "Véier", de: "Vier", en: "Four" } },
      { q: { lb: "Wat ass dat gréisste Organ vum Mënsch?", de: "Was ist das größte Organ des Menschen?", en: "What is the body's largest organ?" },
        a: { lb: "D'Haut", de: "Die Haut", en: "The skin" } },
      { q: { lb: "Ongeféier wéi vill Schanken huet en Erwuessene?", de: "Wie viele Knochen hat ein Erwachsener etwa?", en: "Roughly how many bones does an adult have?" },
        a: { lb: "206", de: "206", en: "206" } },
      { q: { lb: "Wéi ee Organ pompelt d'Blutt?", de: "Welches Organ pumpt das Blut?", en: "Which organ pumps the blood?" },
        a: { lb: "D'Häerz", de: "Das Herz", en: "The heart" } },
      { q: { lb: "Wou gëtt de Sauerstoff an d'Blutt opgeholl?", de: "Wo wird Sauerstoff ins Blut aufgenommen?", en: "Where does oxygen enter the blood?" },
        a: { lb: "An de Longen", de: "In den Lungen", en: "In the lungs" } },
    ]},
    { name: { lb: "Physik", de: "Physik", en: "Physics" }, clues: [
      { q: { lb: "Bei wéi vill Grad Celsius kacht Waasser um Mieresspigel?", de: "Bei wie viel Grad kocht Wasser auf Meereshöhe?", en: "At what temperature does water boil at sea level?" },
        a: { lb: "100 °C", de: "100 °C", en: "100 °C" } },
      { q: { lb: "Bei wéi vill Grad gefréiert Waasser?", de: "Bei wie viel Grad friert Wasser?", en: "At what temperature does water freeze?" },
        a: { lb: "0 °C", de: "0 °C", en: "0 °C" } },
      { q: { lb: "Wat ass méi séier: Liicht oder Toun?", de: "Was ist schneller: Licht oder Schall?", en: "Which is faster: light or sound?" },
        a: { lb: "D'Liicht", de: "Das Licht", en: "Light" } },
      { q: { lb: "Wéi eng Kraaft zitt alles op d'Äerd?", de: "Welche Kraft zieht alles zur Erde?", en: "Which force pulls everything to Earth?" },
        a: { lb: "D'Gravitatioun", de: "Die Gravitation", en: "Gravity" } },
      { q: { lb: "Wéi eng chemesch Formel huet Waasser?", de: "Welche chemische Formel hat Wasser?", en: "What is the chemical formula for water?" },
        a: { lb: "H₂O", de: "H₂O", en: "H₂O" } },
    ]},
  ],
},
];
