"""Small, fixed UI vocabulary for the client-preview template."""

UI = {
    "fr": {
        "preview": "Aperçu — ce site n'est pas encore le site officiel de {name}.",
        "preview_help": "Vous souhaitez le modifier ou le retirer ?",
        "preview_contact": "Écrivez à Ian",
        "close_preview": "Fermer l'aperçu",
        "menu": "La carte",
        "booking": "Réserver une table",
        "faq": "Questions fréquentes",
        "rating": "Avis Google",
        "reviews": "avis",
        "required": "Champ obligatoire",
        "booking_confirmation": "Votre demande",
        "booking_demo": "Ceci est une démonstration : rien n'a été envoyé et rien n'est enregistré. Quand vous voulez, je branche ce formulaire sur votre boîte mail.",
        "about": "Le bistrot",
        "gallery": "En images",
        "hours": "Horaires",
        "contact": "Nous trouver",
        "call": "Appeler",
        "directions": "Itinéraire",
        "email": "E-mail",
        "address": "Adresse",
        "map": "Voir sur OpenStreetMap",
        "closed": "Fermé",
        "legal": "Mentions légales",
        "operator": "Exploitant",
        "legal_address": "Adresse",
        "legal_email": "E-mail",
        "legal_phone": "Téléphone",
        "rcs": "RCS",
        "tva": "TVA",
        "placeholder": "[à compléter]",
        "skip": "Aller au contenu",
        "stock_photo_notice": "Photos d'illustration — elles ne montrent pas {name}. Envoyez-moi vos propres photos et je les remplace.",
        "mixed_photo_notice": "Certaines photos sont encore des images d'illustration. Envoyez-moi les vôtres et je remplace le reste.",
        "photo_credits": "Crédits photo",
        "unknown_author": "Auteur inconnu",
    },
    "de": {
        "preview": "Vorschau — diese Website ist noch nicht die offizielle Website von {name}.",
        "preview_help": "Möchten Sie sie ändern oder entfernen lassen?",
        "preview_contact": "Ian schreiben",
        "close_preview": "Vorschau schließen",
        "menu": "Speisekarte",
        "booking": "Tisch reservieren",
        "faq": "Häufige Fragen",
        "rating": "Google-Bewertungen",
        "reviews": "Bewertungen",
        "required": "Pflichtfeld",
        "booking_confirmation": "Ihre Anfrage",
        "booking_demo": "Dies ist eine Demonstration: Es wurde nichts gesendet und nichts gespeichert. Auf Wunsch verbinde ich dieses Formular mit Ihrem Postfach.",
        "about": "Das Bistro",
        "gallery": "Impressionen",
        "hours": "Öffnungszeiten",
        "contact": "Kontakt",
        "call": "Anrufen",
        "directions": "Route",
        "email": "E-Mail",
        "address": "Adresse",
        "map": "Auf OpenStreetMap ansehen",
        "closed": "Geschlossen",
        "legal": "Impressum",
        "operator": "Betreiber",
        "legal_address": "Adresse",
        "legal_email": "E-Mail",
        "legal_phone": "Telefon",
        "rcs": "RCS",
        "tva": "MwSt.",
        "placeholder": "[zu ergänzen]",
        "skip": "Zum Inhalt",
        "stock_photo_notice": "Illustrationsfotos — sie zeigen nicht {name}. Schicken Sie mir Ihre eigenen Fotos, dann ersetze ich sie.",
        "mixed_photo_notice": "Einige Fotos sind noch Illustrationsbilder. Schicken Sie mir Ihre eigenen, dann ersetze ich den Rest.",
        "photo_credits": "Bildnachweise",
        "unknown_author": "Unbekannter Urheber",
    },
    "en": {
        "preview": "Preview — this site is not yet the official website of {name}.",
        "preview_help": "Would you like it changed or removed?",
        "preview_contact": "Email Ian",
        "close_preview": "Close preview",
        "menu": "Menu",
        "booking": "Book a table",
        "faq": "Frequently asked questions",
        "rating": "Google reviews",
        "reviews": "reviews",
        "required": "Required field",
        "booking_confirmation": "Your request",
        "booking_demo": "This is a demonstration: nothing was sent and nothing is stored. Whenever you like, I can connect this form to your mailbox.",
        "about": "The bistro",
        "gallery": "Gallery",
        "hours": "Opening hours",
        "contact": "Find us",
        "call": "Call",
        "directions": "Directions",
        "email": "Email",
        "address": "Address",
        "map": "View on OpenStreetMap",
        "closed": "Closed",
        "legal": "Legal notice",
        "operator": "Operator",
        "legal_address": "Address",
        "legal_email": "Email",
        "legal_phone": "Phone",
        "rcs": "Trade register",
        "tva": "VAT",
        "placeholder": "[to be completed]",
        "skip": "Skip to content",
        "stock_photo_notice": "Illustration photos — they do not show {name}. Send me your own photos and I will replace them.",
        "mixed_photo_notice": "Some photos are still stock images. Send me your own and I will replace the rest.",
        "photo_credits": "Photo credits",
        "unknown_author": "Unknown author",
    },
}
