"""Small, fixed UI vocabulary for the client-preview template."""

UI = {
    "fr": {
        "preview": "Aperçu — ce site n'est pas encore le site officiel de {name}.",
        "preview_help": "Vous souhaitez le modifier ou le retirer ?",
        "preview_contact": "Écrivez à Ian",
        "close_preview": "Fermer l'aperçu",
        "menu": "La carte",
        "about": "Le bistrot",
        "gallery": "En images",
        "hours": "Horaires",
        "contact": "Nous trouver",
        "call": "Appeler",
        "directions": "Itinéraire",
        "email": "E-mail",
        "address": "Adresse",
        "map": "Voir sur OpenStreetMap",
        "closed": "Fermé",
        "legal": "Mentions légales",
        "operator": "Exploitant",
        "legal_address": "Adresse",
        "legal_email": "E-mail",
        "legal_phone": "Téléphone",
        "rcs": "RCS",
        "tva": "TVA",
        "placeholder": "[à compléter]",
        "skip": "Aller au contenu",
    },
    "de": {
        "preview": "Vorschau — diese Website ist noch nicht die offizielle Website von {name}.",
        "preview_help": "Möchten Sie sie ändern oder entfernen lassen?",
        "preview_contact": "Ian schreiben",
        "close_preview": "Vorschau schließen",
        "menu": "Speisekarte",
        "about": "Das Bistro",
        "gallery": "Impressionen",
        "hours": "Öffnungszeiten",
        "contact": "Kontakt",
        "call": "Anrufen",
        "directions": "Route",
        "email": "E-Mail",
        "address": "Adresse",
        "map": "Auf OpenStreetMap ansehen",
        "closed": "Geschlossen",
        "legal": "Impressum",
        "operator": "Betreiber",
        "legal_address": "Adresse",
        "legal_email": "E-Mail",
        "legal_phone": "Telefon",
        "rcs": "RCS",
        "tva": "MwSt.",
        "placeholder": "[zu ergänzen]",
        "skip": "Zum Inhalt",
    },
    "en": {
        "preview": "Preview — this site is not yet the official website of {name}.",
        "preview_help": "Would you like it changed or removed?",
        "preview_contact": "Email Ian",
        "close_preview": "Close preview",
        "menu": "Menu",
        "about": "The bistro",
        "gallery": "Gallery",
        "hours": "Opening hours",
        "contact": "Find us",
        "call": "Call",
        "directions": "Directions",
        "email": "Email",
        "address": "Address",
        "map": "View on OpenStreetMap",
        "closed": "Closed",
        "legal": "Legal notice",
        "operator": "Operator",
        "legal_address": "Address",
        "legal_email": "Email",
        "legal_phone": "Phone",
        "rcs": "Trade register",
        "tva": "VAT",
        "placeholder": "[to be completed]",
        "skip": "Skip to content",
    },
}
