"""UI strings for the generated trail pages — DE / FR / EN / LB."""

LANG_NAMES = {"de": "Deutsch", "fr": "Français", "en": "English", "lb": "Lëtzebuergesch"}

REGIONS = {
    "center": {"de": "Zentrum / Guttland", "fr": "Centre / Guttland", "en": "Centre / Guttland", "lb": "Zentrum / Guttland"},
    "mullerthal": {"de": "Müllerthal – Kleine Luxemburger Schweiz", "fr": "Mullerthal – Petite Suisse", "en": "Mullerthal – Little Switzerland", "lb": "Mëllerdall – Kleng Lëtzebuerger Schwäiz"},
    "moselle": {"de": "Mosel", "fr": "Moselle", "en": "Moselle", "lb": "Musel"},
    "minett": {"de": "Minett – Rote Erde", "fr": "Minett – Terres Rouges", "en": "Minett – Red Rocks", "lb": "Minett – Rout Äerd"},
    "eislek": {"de": "Éislek – Ardennen", "fr": "Éislek – Ardennes", "en": "Éislek – Ardennes", "lb": "Éislek – Ardennen"},
}

DIFFICULTIES = {
    "easy": {"de": "leicht", "fr": "facile", "en": "easy", "lb": "einfach"},
    "moderate": {"de": "mittel", "fr": "moyenne", "en": "moderate", "lb": "mëttelschwéier"},
    "hard": {"de": "anspruchsvoll", "fr": "exigeante", "en": "challenging", "lb": "schwéier"},
}

EXTRA = {
    "de": {"fact_gain": "Höhenmeter", "photos_title": "Eindrücke vom Weg",
           "profile_title": "Höhenprofil", "photo_via": "via Wikimedia Commons",
           "dl_gpx": "GPX-Datei laden", "open_komoot": "In Komoot planen",
           "open_start": "Startpunkt in Google Maps",
           "sister_mtb": "🚵 Auch entdecken: Mountainbike-Touren in Luxemburg",
           "sister_hiking": "🥾 Auch entdecken: Autopédestre-Wanderwege in Luxemburg",
           "map_link": "🗺️ Alle Wege auf einer Karte ansehen",
           "map_button": "🗺️ Karte öffnen",
           "search_placeholder": "Ort oder Weg suchen …",
           "search_label": "Wege durchsuchen",
           "no_results": "Kein Weg passt zu dieser Suche."},
    "fr": {"fact_gain": "Dénivelé +", "photos_title": "Impressions du parcours",
           "profile_title": "Profil altimétrique", "photo_via": "via Wikimedia Commons",
           "dl_gpx": "Télécharger le GPX", "open_komoot": "Planifier dans Komoot",
           "open_start": "Départ dans Google Maps",
           "sister_mtb": "🚵 À découvrir aussi : les circuits VTT du Luxembourg",
           "sister_hiking": "🥾 À découvrir aussi : les Auto-Pédestres du Luxembourg",
           "map_link": "🗺️ Voir tous les parcours sur une carte",
           "map_button": "🗺️ Ouvrir la carte",
           "search_placeholder": "Rechercher une localité ou un circuit …",
           "search_label": "Rechercher un circuit",
           "no_results": "Aucun circuit ne correspond à cette recherche."},
    "en": {"fact_gain": "Elevation gain", "photos_title": "Impressions from the trail",
           "profile_title": "Elevation profile", "photo_via": "via Wikimedia Commons",
           "dl_gpx": "Download GPX", "open_komoot": "Plan in Komoot",
           "open_start": "Start point in Google Maps",
           "sister_mtb": "🚵 Also worth exploring: Luxembourg's MTB tours",
           "sister_hiking": "🥾 Also worth exploring: Luxembourg's Auto-Pédestre walks",
           "map_link": "🗺️ See every route on one map",
           "map_button": "🗺️ Open the map",
           "search_placeholder": "Search a place or trail …",
           "search_label": "Search trails",
           "no_results": "No trail matches that search."},
    "lb": {
        "fact_gain": "Héichtemeter",
        "photos_title": "Fotoe vum Wee",
        "profile_title": "Héichteprofil",
        "photo_via": "iwwer Wikimedia Commons",
        "dl_gpx": "GPX-Datei eroflueden",
        "open_komoot": "A Komoot plangen",
        "open_start": "Startpunkt op Google Maps",
        "sister_mtb": "🚵 Och kucken: MTB-Touren zu Lëtzebuerg",
        "sister_hiking": "🥾 Och kucken: Auto-Pédestre-Weeër zu Lëtzebuerg",
        "map_link": "🗺️ All d’Weeër op enger Kaart kucken",
        "map_button": "🗺️ Kaart opmaachen",
        "search_placeholder": "Eng Uertschaft oder e Wee sichen …",
        "search_label": "Weeër sichen",
        "no_results": "Kee Wee passt zu dëser Sich."
    },
}

UI_MTB = {
    "de": {
        "site_name": "MTB Trails Luxemburg",
        "index_title": "MTB Trails Luxemburg — alle Mountainbike-Touren mit Karte, GPX & Busanreise",
        "index_meta": "Die ausgeschilderten Mountainbike-Touren in Luxemburg: interaktive Karte, Höhenprofil, GPX-Download und Anreise mit dem kostenlosen Bus zu jeder Tour.",
        "index_h1": "Mountainbike-Touren in Luxemburg",
        "index_intro": [
            "Luxemburg hat ein dichtes Netz ausgeschilderter Mountainbike-Rundtouren: von den nationalen MTB-Strecken über die RedRock-Trails auf den alten Bergbauflächen des Südens bis zu lokalen Runden im Éislek und im Müllerthal. Die meisten sind dauerhaft beschildert und starten in Orten, die mit dem — landesweit kostenlosen — Bus erreichbar sind.",
            "Diese Seite stellt die Touren einzeln vor: mit interaktiver Karte, Länge, Höhenprofil, ungefährer Fahrzeit, GPX-Download und den Haltestellen an der Strecke. Alle Streckendaten stammen aus OpenStreetMap, die Haltestellen aus den offiziellen Fahrplandaten Luxemburgs.",
        ],
        "trail_title": "{name} — MTB-Tour {commune} | MTB Trails Luxemburg",
        "trail_meta": "{name}: {length} km Mountainbike-Rundtour bei {commune} ({region}). Karte, Höhenprofil, GPX und Anreise mit dem Bus.",
        "photo_alt": "Eindruck von der Mountainbike-Tour {name} bei {commune}",
        "nearby_title": "Touren in der Nähe",
        "nearby_dist": "{d} km entfernt",
        "facts_title": "Auf einen Blick",
        "fact_length": "Länge",
        "fact_duration": "Fahrzeit",
        "fact_difficulty": "Schwierigkeit",
        "fact_region": "Region",
        "fact_commune": "Gemeinde",
        "fact_type": "Typ",
        "fact_type_value": "Rundtour (MTB)",
        "duration_fmt": "ca. {} Std.",
        "highlights_title": "Highlights",
        "map_title": "Karte",
        "map_note": "Streckenverlauf aus OpenStreetMap — kleine Abweichungen vor Ort sind möglich. Maßgeblich ist die MTB-Beschilderung an der Strecke.",
        "bus_title": "Anreise mit dem Bus",
        "bus_intro": "Der öffentliche Verkehr ist in Luxemburg kostenlos. Diese Haltestellen liegen an der Strecke:",
        "bus_dist": "{} m von der Strecke",
        "bus_lines": "Linien",
        "bus_no_lines": "siehe Fahrplan",
        "bus_live": "Live-Abfahrten für alle Haltestellen: ian.lu/bus",
        "all_trails": "Alle Touren",
        "filter_all": "Alle Regionen",
        "footer_note": "Ein Projekt von ian.lu · Streckendaten © OpenStreetMap-Mitwirkende · Fahrplandaten: data.public.lu",
        "breadcrumb_home": "MTB Trails",
        "lang_switch_label": "Sprache",
        "card_cta": "Zur Tour",
    },
    "fr": {
        "site_name": "MTB Trails Luxembourg",
        "index_title": "MTB Trails Luxembourg — tous les circuits VTT avec carte, GPX et accès en bus",
        "index_meta": "Les circuits VTT balisés du Luxembourg : carte interactive, profil altimétrique, GPX à télécharger et accès en bus gratuit pour chaque tour.",
        "index_h1": "Les circuits VTT du Luxembourg",
        "index_intro": [
            "Le Luxembourg dispose d'un réseau dense de circuits VTT balisés : des tours nationaux aux trails RedRock sur les anciennes friches minières du sud, en passant par les boucles locales de l'Éislek et du Mullerthal. La plupart sont balisés en permanence et partent de localités accessibles en bus — gratuit dans tout le pays.",
            "Ce site présente les circuits un par un : carte interactive, distance, profil altimétrique, durée approximative, GPX à télécharger et arrêts de bus sur le parcours. Les tracés proviennent d'OpenStreetMap, les arrêts des données horaires officielles du Luxembourg.",
        ],
        "trail_title": "{name} — circuit VTT à {commune} | MTB Trails Luxembourg",
        "trail_meta": "{name} : circuit VTT de {length} km près de {commune} ({region}). Carte, profil, GPX et accès en bus.",
        "photo_alt": "Impression du circuit VTT {name} près de {commune}",
        "nearby_title": "Circuits à proximité",
        "nearby_dist": "à {d} km",
        "facts_title": "En bref",
        "fact_length": "Distance",
        "fact_duration": "Durée",
        "fact_difficulty": "Difficulté",
        "fact_region": "Région",
        "fact_commune": "Commune",
        "fact_type": "Type",
        "fact_type_value": "Boucle (VTT)",
        "duration_fmt": "env. {} h",
        "highlights_title": "Points forts",
        "map_title": "Carte",
        "map_note": "Tracé issu d'OpenStreetMap — de petits écarts sur le terrain sont possibles. Le balisage VTT sur place fait foi.",
        "bus_title": "Y aller en bus",
        "bus_intro": "Les transports publics sont gratuits au Luxembourg. Ces arrêts se trouvent sur le parcours :",
        "bus_dist": "à {} m du parcours",
        "bus_lines": "Lignes",
        "bus_no_lines": "voir horaires",
        "bus_live": "Départs en direct pour tous les arrêts : ian.lu/bus",
        "all_trails": "Tous les circuits",
        "filter_all": "Toutes les régions",
        "footer_note": "Un projet de ian.lu · Tracés © contributeurs OpenStreetMap · Horaires : data.public.lu",
        "breadcrumb_home": "MTB Trails",
        "lang_switch_label": "Langue",
        "card_cta": "Voir le circuit",
    },
    "en": {
        "site_name": "MTB Trails Luxembourg",
        "index_title": "MTB Trails Luxembourg — every marked mountain-bike loop with map, GPX & bus access",
        "index_meta": "Luxembourg's waymarked mountain-bike loops: interactive map, elevation profile, GPX download and free-bus access for every tour.",
        "index_h1": "Luxembourg's mountain-bike loops",
        "index_intro": [
            "Luxembourg has a dense network of waymarked mountain-bike loops: national MTB tours, the RedRock trails on the former mining land of the south, and local circuits in the Éislek and the Mullerthal. Most are permanently signposted and start in villages you can reach by bus — free of charge nationwide.",
            "This site presents the tours one by one: interactive map, distance, elevation profile, approximate riding time, GPX download and the bus stops on the route. Route data comes from OpenStreetMap, stop data from Luxembourg's official timetable feed.",
        ],
        "trail_title": "{name} — MTB loop in {commune} | MTB Trails Luxembourg",
        "trail_meta": "{name}: {length} km mountain-bike loop near {commune} ({region}). Map, elevation profile, GPX and how to get there by bus.",
        "photo_alt": "View from the {name} mountain-bike loop near {commune}",
        "nearby_title": "Rides nearby",
        "nearby_dist": "{d} km away",
        "facts_title": "At a glance",
        "fact_length": "Distance",
        "fact_duration": "Riding time",
        "fact_difficulty": "Difficulty",
        "fact_region": "Region",
        "fact_commune": "Commune",
        "fact_type": "Type",
        "fact_type_value": "Loop (MTB)",
        "duration_fmt": "approx. {} h",
        "highlights_title": "Highlights",
        "map_title": "Map",
        "map_note": "Route line from OpenStreetMap — small deviations on the ground are possible. The MTB signposts on site are authoritative.",
        "bus_title": "Getting there by bus",
        "bus_intro": "Public transport is free in Luxembourg. These stops are on the route:",
        "bus_dist": "{} m from the route",
        "bus_lines": "Lines",
        "bus_no_lines": "see timetable",
        "bus_live": "Live departures for every stop: ian.lu/bus",
        "all_trails": "All tours",
        "filter_all": "All regions",
        "footer_note": "A project by ian.lu · Route data © OpenStreetMap contributors · Timetables: data.public.lu",
        "breadcrumb_home": "MTB Trails",
        "lang_switch_label": "Language",
        "card_cta": "View tour",
    },
    "lb": {
        "site_name": "MTB Trails Lëtzebuerg",
        "index_title": "MTB Trails Lëtzebuerg — all d’Touren mat Kaart, GPX an Urees mam Bus",
        "index_meta": "Déi markéiert MTB-Touren zu Lëtzebuerg: eng interaktiv Kaart, Héichteprofil, GPX-Datei an Urees mam gratis Bus fir all Tour.",
        "index_h1": "MTB-Touren zu Lëtzebuerg",
        "index_intro": [
            "Zu Lëtzebuerg gëtt et vill markéiert MTB-Ronnen: national Circuiten, RedRock-Trails op de fréieren Ofbaugebidder am Süden a lokal Ronnen am Éislek an am Mëllerdall. Déi meescht si permanent markéiert a fänken an Uertschaften un, déi mam Bus erreechbar sinn. De Bus ass am ganze Land gratis.",
            "Op dëser Säit gëtt all Tour eenzel virgestallt: mat enger interaktiver Kaart, der Längt, dem Héichteprofil, der geschater Fuerzäit, enger GPX-Datei an de Busarrêten op der Streck. D’Streckendate kommen aus OpenStreetMap. D’Busarrête kommen aus den offizielle Fuerplangdate vu Lëtzebuerg."
        ],
        "trail_title": "{name} — MTB-Tour ronderëm {commune} | MTB Trails Lëtzebuerg",
        "trail_meta": "{name}: eng {length} km laang MTB-Ronn ronderëm {commune} ({region}). Kaart, Héichteprofil, GPX an Urees mam Bus.",
        "photo_alt": "Foto vun der MTB-Tour {name} bei {commune}",
        "nearby_title": "MTB-Touren an der Géigend",
        "nearby_dist": "{d} km ewech",
        "facts_title": "Op ee Bléck",
        "fact_length": "Längt",
        "fact_duration": "Fuerzäit",
        "fact_difficulty": "Schwieregkeet",
        "fact_region": "Regioun",
        "fact_commune": "Gemeng",
        "fact_type": "Typ",
        "fact_type_value": "Ronn (MTB)",
        "duration_fmt": "ongeféier {} h",
        "highlights_title": "Wat et ënnerwee ze gesi gëtt",
        "map_title": "Kaart",
        "map_note": "De Verlaf vun der Streck kënnt aus OpenStreetMap. Op der Plaz si kleng Ofwäichunge méiglech. Follegt den MTB-Markéierungen op der Streck.",
        "bus_title": "Urees mam Bus",
        "bus_intro": "Den ëffentlechen Transport ass zu Lëtzebuerg gratis. Dës Busarrête leien op der Streck:",
        "bus_dist": "{} m vun der Streck",
        "bus_lines": "Linnen",
        "bus_no_lines": "kuckt de Fuerplang",
        "bus_live": "Aktuell Departen op alle Busarrêten: ian.lu/bus",
        "all_trails": "All d’Touren",
        "filter_all": "All d’Regiounen",
        "footer_note": "E Projet vun ian.lu · Streckendaten © OpenStreetMap-Mataarbechter · Fuerplangdaten: data.public.lu",
        "breadcrumb_home": "MTB Trails",
        "lang_switch_label": "Sprooch",
        "card_cta": "Den Tour kucken"
    },
}

UI = {
    "de": {
        "site_name": "Autopédestres Luxemburg",
        "index_title": "Autopédestres Luxemburg — alle Rundwanderwege mit Karte & Busanreise",
        "index_meta": "Die Autopédestre-Rundwanderwege in Luxemburg: interaktive Karte, Länge, Dauer, Schwierigkeit und Anreise mit dem kostenlosen Bus zu jedem Weg.",
        "index_h1": "Autopédestre-Rundwanderwege in Luxemburg",
        "index_intro": [
            "Die Autopédestres sind Luxemburgs klassische Rundwanderwege: {n} lokale Schleifen im ganzen Land, dauerhaft mit dem blauen Symbol markiert und so angelegt, dass man immer wieder am Ausgangspunkt ankommt. Viele wurden vor Jahrzehnten für Ausflügler mit dem Auto geschaffen — daher der Name — aber heute erreicht man die meisten bequem mit dem Bus, denn der öffentliche Verkehr ist in ganz Luxemburg kostenlos.",
            "Diese Seite stellt die Wege einzeln vor — mit interaktiver Karte, Länge, ungefährer Gehzeit, Schwierigkeit und den Bushaltestellen direkt am Weg. Die Liste folgt dem offiziellen Verzeichnis auf geoportail.lu, das von 201 auf heute {n} Rundwege gekürzt wurde — was hier steht, ist also tatsächlich noch markiert. Die Streckendaten stammen aus OpenStreetMap und aus den offenen Daten der Kataster- und Topografieverwaltung, die Haltestellen aus den offiziellen Fahrplandaten Luxemburgs.",
        ],
        "trail_title": "{name} — Rundwanderweg {commune} | Autopédestres Luxemburg",
        "trail_meta": "{name}: {length} km Rundwanderweg bei {commune} ({region}). Karte, Gehzeit, Schwierigkeit und Anreise mit dem Bus.",
        "photo_alt": "Eindruck vom Wanderweg {name} bei {commune}",
        "nearby_title": "Wanderwege in der Nähe",
        "nearby_dist": "{d} km entfernt",
        "facts_title": "Auf einen Blick",
        "fact_length": "Länge",
        "fact_duration": "Gehzeit",
        "fact_difficulty": "Schwierigkeit",
        "fact_region": "Region",
        "fact_commune": "Gemeinde",
        "fact_type": "Typ",
        "fact_type_value": "Rundweg (Autopédestre)",
        "duration_fmt": "ca. {} Std.",
        "highlights_title": "Highlights",
        "map_title": "Karte",
        "map_note": "Streckenverlauf aus OpenStreetMap — kleine Abweichungen vor Ort sind möglich. Maßgeblich ist die blaue Markierung am Weg.",
        "map_note_official": "Streckenverlauf aus den offenen Daten der Kataster- und Topografieverwaltung (data.public.lu / geoportail.lu, CC0) — kleine Abweichungen vor Ort sind möglich. Maßgeblich ist die blaue Markierung am Weg.",
        "bus_title": "Anreise mit dem Bus",
        "bus_intro": "Der öffentliche Verkehr ist in Luxemburg kostenlos. Diese Haltestellen liegen am Weg:",
        "bus_dist": "{} m vom Weg",
        "bus_lines": "Linien",
        "bus_no_lines": "siehe Fahrplan",
        "bus_live": "Live-Abfahrten für alle Haltestellen: ian.lu/bus",
        "all_trails": "Alle Wege",
        "filter_all": "Alle Regionen",
        "footer_note": "Ein Projekt von ian.lu · Streckendaten © OpenStreetMap-Mitwirkende · Fahrplandaten: data.public.lu",
        "breadcrumb_home": "Autopédestres",
        "lang_switch_label": "Sprache",
        "card_cta": "Zum Weg",
    },
    "fr": {
        "site_name": "Auto-Pédestres Luxembourg",
        "index_title": "Auto-Pédestres Luxembourg — toutes les boucles avec carte et accès en bus",
        "index_meta": "Les circuits Auto-Pédestre du Luxembourg : carte interactive, distance, durée, difficulté et accès en bus gratuit pour chaque boucle.",
        "index_h1": "Les circuits Auto-Pédestre du Luxembourg",
        "index_intro": [
            "Les Auto-Pédestres sont les boucles de randonnée classiques du Luxembourg : {n} circuits locaux dans tout le pays, balisés en permanence du symbole bleu et conçus pour vous ramener toujours à votre point de départ. Beaucoup furent créés il y a des décennies pour les excursionnistes en voiture — d'où le nom — mais aujourd'hui la plupart s'atteignent facilement en bus, les transports publics étant gratuits dans tout le Luxembourg.",
            "Ce site présente les circuits un par un — avec carte interactive, distance, durée approximative, difficulté et les arrêts de bus situés directement sur le parcours. La liste suit le répertoire officiel de geoportail.lu, ramené de 201 à {n} boucles — ce qui figure ici est donc encore balisé sur le terrain. Les tracés proviennent d'OpenStreetMap et des données ouvertes de l'Administration du cadastre et de la topographie, les arrêts des données horaires officielles du Luxembourg.",
        ],
        "trail_title": "{name} — boucle de randonnée à {commune} | Auto-Pédestres Luxembourg",
        "trail_meta": "{name} : boucle de {length} km près de {commune} ({region}). Carte, durée, difficulté et accès en bus.",
        "photo_alt": "Impression du sentier {name} près de {commune}",
        "nearby_title": "Sentiers à proximité",
        "nearby_dist": "à {d} km",
        "facts_title": "En bref",
        "fact_length": "Distance",
        "fact_duration": "Durée",
        "fact_difficulty": "Difficulté",
        "fact_region": "Région",
        "fact_commune": "Commune",
        "fact_type": "Type",
        "fact_type_value": "Boucle (Auto-Pédestre)",
        "duration_fmt": "env. {} h",
        "highlights_title": "Points forts",
        "map_title": "Carte",
        "map_note": "Tracé issu d'OpenStreetMap — de petits écarts sur le terrain sont possibles. Le balisage bleu sur place fait foi.",
        "map_note_official": "Tracé issu des données ouvertes de l'Administration du cadastre et de la topographie (data.public.lu / geoportail.lu, CC0) — de petits écarts sur le terrain sont possibles. Le balisage bleu sur place fait foi.",
        "bus_title": "Y aller en bus",
        "bus_intro": "Les transports publics sont gratuits au Luxembourg. Ces arrêts se trouvent sur le parcours :",
        "bus_dist": "à {} m du sentier",
        "bus_lines": "Lignes",
        "bus_no_lines": "voir horaires",
        "bus_live": "Départs en direct pour tous les arrêts : ian.lu/bus",
        "all_trails": "Tous les circuits",
        "filter_all": "Toutes les régions",
        "footer_note": "Un projet de ian.lu · Tracés © contributeurs OpenStreetMap · Horaires : data.public.lu",
        "breadcrumb_home": "Auto-Pédestres",
        "lang_switch_label": "Langue",
        "card_cta": "Voir le circuit",
    },
    "en": {
        "site_name": "Auto-Pédestres Luxembourg",
        "index_title": "Auto-Pédestres Luxembourg — every loop trail with map & bus access",
        "index_meta": "Luxembourg's Auto-Pédestre loop walks: interactive map, distance, duration, difficulty and free-bus access for every trail.",
        "index_h1": "Luxembourg's Auto-Pédestre loop trails",
        "index_intro": [
            "The Auto-Pédestres are Luxembourg's classic circular walks: {n} local loops across the country, permanently waymarked with the blue symbol and always bringing you back to where you started. Many were laid out decades ago for day-trippers arriving by car — hence the name — but today most are easy to reach by bus, since public transport is free throughout Luxembourg.",
            "This site presents the trails one by one — with an interactive map, distance, approximate walking time, difficulty and the bus stops right on the route. The list follows the official register on geoportail.lu, which was cut from 201 circuits to today's {n}, so everything here is still waymarked on the ground. Route lines come from OpenStreetMap and from the Land Registry and Topography Administration's open data, stop data from Luxembourg's official timetable feed.",
        ],
        "trail_title": "{name} — loop walk in {commune} | Auto-Pédestres Luxembourg",
        "trail_meta": "{name}: {length} km loop walk near {commune} ({region}). Map, walking time, difficulty and how to get there by bus.",
        "photo_alt": "View from the {name} trail near {commune}",
        "nearby_title": "Trails nearby",
        "nearby_dist": "{d} km away",
        "facts_title": "At a glance",
        "fact_length": "Distance",
        "fact_duration": "Duration",
        "fact_difficulty": "Difficulty",
        "fact_region": "Region",
        "fact_commune": "Commune",
        "fact_type": "Type",
        "fact_type_value": "Loop (Auto-Pédestre)",
        "duration_fmt": "approx. {} h",
        "highlights_title": "Highlights",
        "map_title": "Map",
        "map_note": "Route line from OpenStreetMap — small deviations on the ground are possible. The blue waymarks on site are authoritative.",
        "map_note_official": "Route line from the open data of Luxembourg's cadastre and topography administration (data.public.lu / geoportail.lu, CC0) — small deviations on the ground are possible. The blue waymarks on site are authoritative.",
        "bus_title": "Getting there by bus",
        "bus_intro": "Public transport is free in Luxembourg. These stops are on the route:",
        "bus_dist": "{} m from the trail",
        "bus_lines": "Lines",
        "bus_no_lines": "see timetable",
        "bus_live": "Live departures for every stop: ian.lu/bus",
        "all_trails": "All trails",
        "filter_all": "All regions",
        "footer_note": "A project by ian.lu · Route data © OpenStreetMap contributors · Timetables: data.public.lu",
        "breadcrumb_home": "Auto-Pédestres",
        "lang_switch_label": "Language",
        "card_cta": "View trail",
    },
    "lb": {
        "site_name": "Auto-Pédestres Lëtzebuerg",
        "index_title": "Auto-Pédestres Lëtzebuerg — all d’Ronne mat Kaart an Urees mam Bus",
        "index_meta": "D’Auto-Pédestre-Weeër zu Lëtzebuerg: eng interaktiv Kaart, Längt, Dauer, Schwieregkeet an Urees mam gratis Bus fir all Ronn.",
        "index_h1": "Auto-Pédestre-Weeër zu Lëtzebuerg",
        "index_intro": [
            "D’Auto-Pédestres sinn déi klassesch Wanderweeër zu Lëtzebuerg: {n} Ronnen uechter d’Land, déi mat engem bloe Symbol markéiert sinn an ëmmer erëm op de Startpunkt zréckféieren. Vill dovu goufe viru Joerzéngte fir Leit ugeluecht, déi mam Auto wandere koumen — dohier den Numm. Haut kënnt ee bei déi meescht bequem mam Bus. Den ëffentlechen Transport ass am ganze Land gratis.",
            "Op dëser Säit gëtt all Wee eenzel virgestallt: mat enger interaktiver Kaart, der Längt, der geschater Dauer, der Schwieregkeet an de Busarrêten direkt um Wee. D’Lëscht entsprécht dem offizielle Verzeechnes op geoportail.lu, dat vun 201 op {n} Ronne verkierzt gouf. D’Weeër op dëser Lëscht sinn also nach markéiert. D’Streckendate kommen aus OpenStreetMap an aus den oppenen Date vun der Kataster- an Topografieverwaltung. D’Busarrête kommen aus den offizielle Fuerplangdate vu Lëtzebuerg."
        ],
        "trail_title": "{name} — Wanderung ronderëm {commune} | Auto-Pédestres Lëtzebuerg",
        "trail_meta": "{name}: eng {length} km laang Ronn ronderëm {commune} ({region}). Kaart, Dauer, Schwieregkeet an Urees mam Bus.",
        "photo_alt": "Foto vum Wanderwee {name} bei {commune}",
        "nearby_title": "Wanderweeër an der Géigend",
        "nearby_dist": "{d} km ewech",
        "facts_title": "Op ee Bléck",
        "fact_length": "Längt",
        "fact_duration": "Dauer vun der Wanderung",
        "fact_difficulty": "Schwieregkeet",
        "fact_region": "Regioun",
        "fact_commune": "Gemeng",
        "fact_type": "Typ",
        "fact_type_value": "Ronn (Auto-Pédestre)",
        "duration_fmt": "ongeféier {} h",
        "highlights_title": "Wat et ënnerwee ze gesi gëtt",
        "map_title": "Kaart",
        "map_note": "De Verlaf vum Wee kënnt aus OpenStreetMap. Op der Plaz si kleng Ofwäichunge méiglech. Follegt de bloe Markéierungen um Wee.",
        "map_note_official": "De Verlaf vum Wee kënnt aus den oppenen Date vun der Kataster- an Topografieverwaltung (data.public.lu / geoportail.lu, CC0). Op der Plaz si kleng Ofwäichunge méiglech. Follegt de bloe Markéierungen um Wee.",
        "bus_title": "Urees mam Bus",
        "bus_intro": "Den ëffentlechen Transport ass zu Lëtzebuerg gratis. Dës Busarrête leien um Wee:",
        "bus_dist": "{} m vum Wee",
        "bus_lines": "Linnen",
        "bus_no_lines": "kuckt de Fuerplang",
        "bus_live": "Aktuell Departen op alle Busarrêten: ian.lu/bus",
        "all_trails": "All d’Weeër",
        "filter_all": "All d’Regiounen",
        "footer_note": "E Projet vun ian.lu · Streckendaten © OpenStreetMap-Mataarbechter · Fuerplangdaten: data.public.lu",
        "breadcrumb_home": "Auto-Pédestres",
        "lang_switch_label": "Sprooch",
        "card_cta": "De Wee kucken"
    },
}

UI_BY_CAT = {"hiking": UI, "mtb": UI_MTB}
