"""UI strings for the generated trail pages — DE / FR / EN.

Luxembourgish is deliberately absent: AdSense only supports DE/FR/EN and the
pages must render exactly the language their <html lang> declares.
"""

LANG_NAMES = {"de": "Deutsch", "fr": "Français", "en": "English"}

REGIONS = {
    "center": {"de": "Zentrum / Guttland", "fr": "Centre / Guttland", "en": "Centre / Guttland"},
    "mullerthal": {"de": "Müllerthal – Kleine Luxemburger Schweiz", "fr": "Mullerthal – Petite Suisse", "en": "Mullerthal – Little Switzerland"},
    "moselle": {"de": "Mosel", "fr": "Moselle", "en": "Moselle"},
    "minett": {"de": "Minett – Rote Erde", "fr": "Minett – Terres Rouges", "en": "Minett – Red Rocks"},
    "eislek": {"de": "Éislek – Ardennen", "fr": "Éislek – Ardennes", "en": "Éislek – Ardennes"},
}

DIFFICULTIES = {
    "easy": {"de": "leicht", "fr": "facile", "en": "easy"},
    "moderate": {"de": "mittel", "fr": "moyenne", "en": "moderate"},
    "hard": {"de": "anspruchsvoll", "fr": "exigeante", "en": "challenging"},
}

EXTRA = {
    "de": {"fact_gain": "Höhenmeter", "photos_title": "Eindrücke vom Weg",
           "profile_title": "Höhenprofil", "photo_via": "via Wikimedia Commons",
           "dl_gpx": "GPX-Datei laden", "open_komoot": "In Komoot planen",
           "open_start": "Startpunkt in Google Maps",
           "sister_mtb": "🚵 Auch entdecken: Mountainbike-Touren in Luxemburg",
           "sister_hiking": "🥾 Auch entdecken: Autopédestre-Wanderwege in Luxemburg",
           "map_link": "🗺️ Alle Wege auf einer Karte ansehen"},
    "fr": {"fact_gain": "Dénivelé +", "photos_title": "Impressions du parcours",
           "profile_title": "Profil altimétrique", "photo_via": "via Wikimedia Commons",
           "dl_gpx": "Télécharger le GPX", "open_komoot": "Planifier dans Komoot",
           "open_start": "Départ dans Google Maps",
           "sister_mtb": "🚵 À découvrir aussi : les circuits VTT du Luxembourg",
           "sister_hiking": "🥾 À découvrir aussi : les Auto-Pédestres du Luxembourg",
           "map_link": "🗺️ Voir tous les parcours sur une carte"},
    "en": {"fact_gain": "Elevation gain", "photos_title": "Impressions from the trail",
           "profile_title": "Elevation profile", "photo_via": "via Wikimedia Commons",
           "dl_gpx": "Download GPX", "open_komoot": "Plan in Komoot",
           "open_start": "Start point in Google Maps",
           "sister_mtb": "🚵 Also worth exploring: Luxembourg's MTB tours",
           "sister_hiking": "🥾 Also worth exploring: Luxembourg's Auto-Pédestre walks",
           "map_link": "🗺️ See every route on one map"},
}

UI_MTB = {
    "de": {
        "site_name": "MTB Trails Luxemburg",
        "index_title": "MTB Trails Luxemburg — alle Mountainbike-Touren mit Karte, GPX & Busanreise",
        "index_meta": "Die ausgeschilderten Mountainbike-Touren in Luxemburg: interaktive Karte, Höhenprofil, GPX-Download und Anreise mit dem kostenlosen Bus zu jeder Tour.",
        "index_h1": "Mountainbike-Touren in Luxemburg",
        "index_intro": [
            "Luxemburg hat ein dichtes Netz ausgeschilderter Mountainbike-Rundtouren: von den nationalen MTB-Strecken über die RedRock-Trails auf den alten Bergbauflächen des Südens bis zu lokalen Runden im Éislek und im Müllerthal. Die meisten sind dauerhaft beschildert und starten in Orten, die mit dem — landesweit kostenlosen — Bus erreichbar sind.",
            "Diese Seite stellt die Touren einzeln vor: mit interaktiver Karte, Länge, Höhenprofil, ungefährer Fahrzeit, GPX-Download und den Haltestellen an der Strecke. Alle Streckendaten stammen aus OpenStreetMap, die Haltestellen aus den offiziellen Fahrplandaten Luxemburgs.",
        ],
        "trail_title": "{name} — MTB-Tour {commune} | MTB Trails Luxemburg",
        "trail_meta": "{name}: {length} km Mountainbike-Rundtour bei {commune} ({region}). Karte, Höhenprofil, GPX und Anreise mit dem Bus.",
        "photo_alt": "Eindruck von der Mountainbike-Tour {name} bei {commune}",
        "nearby_title": "Touren in der Nähe",
        "nearby_dist": "{d} km entfernt",
        "facts_title": "Auf einen Blick",
        "fact_length": "Länge",
        "fact_duration": "Fahrzeit",
        "fact_difficulty": "Schwierigkeit",
        "fact_region": "Region",
        "fact_commune": "Gemeinde",
        "fact_type": "Typ",
        "fact_type_value": "Rundtour (MTB)",
        "duration_fmt": "ca. {} Std.",
        "highlights_title": "Highlights",
        "map_title": "Karte",
        "map_note": "Streckenverlauf aus OpenStreetMap — kleine Abweichungen vor Ort sind möglich. Maßgeblich ist die MTB-Beschilderung an der Strecke.",
        "bus_title": "Anreise mit dem Bus",
        "bus_intro": "Der öffentliche Verkehr ist in Luxemburg kostenlos. Diese Haltestellen liegen an der Strecke:",
        "bus_dist": "{} m von der Strecke",
        "bus_lines": "Linien",
        "bus_no_lines": "siehe Fahrplan",
        "bus_live": "Live-Abfahrten für alle Haltestellen: ian.lu/bus",
        "all_trails": "Alle Touren",
        "filter_all": "Alle Regionen",
        "footer_note": "Ein Projekt von ian.lu · Streckendaten © OpenStreetMap-Mitwirkende · Fahrplandaten: data.public.lu",
        "breadcrumb_home": "MTB Trails",
        "lang_switch_label": "Sprache",
        "card_cta": "Zur Tour",
    },
    "fr": {
        "site_name": "MTB Trails Luxembourg",
        "index_title": "MTB Trails Luxembourg — tous les circuits VTT avec carte, GPX et accès en bus",
        "index_meta": "Les circuits VTT balisés du Luxembourg : carte interactive, profil altimétrique, GPX à télécharger et accès en bus gratuit pour chaque tour.",
        "index_h1": "Les circuits VTT du Luxembourg",
        "index_intro": [
            "Le Luxembourg dispose d'un réseau dense de circuits VTT balisés : des tours nationaux aux trails RedRock sur les anciennes friches minières du sud, en passant par les boucles locales de l'Éislek et du Mullerthal. La plupart sont balisés en permanence et partent de localités accessibles en bus — gratuit dans tout le pays.",
            "Ce site présente les circuits un par un : carte interactive, distance, profil altimétrique, durée approximative, GPX à télécharger et arrêts de bus sur le parcours. Les tracés proviennent d'OpenStreetMap, les arrêts des données horaires officielles du Luxembourg.",
        ],
        "trail_title": "{name} — circuit VTT à {commune} | MTB Trails Luxembourg",
        "trail_meta": "{name} : circuit VTT de {length} km près de {commune} ({region}). Carte, profil, GPX et accès en bus.",
        "photo_alt": "Impression du circuit VTT {name} près de {commune}",
        "nearby_title": "Circuits à proximité",
        "nearby_dist": "à {d} km",
        "facts_title": "En bref",
        "fact_length": "Distance",
        "fact_duration": "Durée",
        "fact_difficulty": "Difficulté",
        "fact_region": "Région",
        "fact_commune": "Commune",
        "fact_type": "Type",
        "fact_type_value": "Boucle (VTT)",
        "duration_fmt": "env. {} h",
        "highlights_title": "Points forts",
        "map_title": "Carte",
        "map_note": "Tracé issu d'OpenStreetMap — de petits écarts sur le terrain sont possibles. Le balisage VTT sur place fait foi.",
        "bus_title": "Y aller en bus",
        "bus_intro": "Les transports publics sont gratuits au Luxembourg. Ces arrêts se trouvent sur le parcours :",
        "bus_dist": "à {} m du parcours",
        "bus_lines": "Lignes",
        "bus_no_lines": "voir horaires",
        "bus_live": "Départs en direct pour tous les arrêts : ian.lu/bus",
        "all_trails": "Tous les circuits",
        "filter_all": "Toutes les régions",
        "footer_note": "Un projet de ian.lu · Tracés © contributeurs OpenStreetMap · Horaires : data.public.lu",
        "breadcrumb_home": "MTB Trails",
        "lang_switch_label": "Langue",
        "card_cta": "Voir le circuit",
    },
    "en": {
        "site_name": "MTB Trails Luxembourg",
        "index_title": "MTB Trails Luxembourg — every marked mountain-bike loop with map, GPX & bus access",
        "index_meta": "Luxembourg's waymarked mountain-bike loops: interactive map, elevation profile, GPX download and free-bus access for every tour.",
        "index_h1": "Luxembourg's mountain-bike loops",
        "index_intro": [
            "Luxembourg has a dense network of waymarked mountain-bike loops: national MTB tours, the RedRock trails on the former mining land of the south, and local circuits in the Éislek and the Mullerthal. Most are permanently signposted and start in villages you can reach by bus — free of charge nationwide.",
            "This site presents the tours one by one: interactive map, distance, elevation profile, approximate riding time, GPX download and the bus stops on the route. Route data comes from OpenStreetMap, stop data from Luxembourg's official timetable feed.",
        ],
        "trail_title": "{name} — MTB loop in {commune} | MTB Trails Luxembourg",
        "trail_meta": "{name}: {length} km mountain-bike loop near {commune} ({region}). Map, elevation profile, GPX and how to get there by bus.",
        "photo_alt": "View from the {name} mountain-bike loop near {commune}",
        "nearby_title": "Rides nearby",
        "nearby_dist": "{d} km away",
        "facts_title": "At a glance",
        "fact_length": "Distance",
        "fact_duration": "Riding time",
        "fact_difficulty": "Difficulty",
        "fact_region": "Region",
        "fact_commune": "Commune",
        "fact_type": "Type",
        "fact_type_value": "Loop (MTB)",
        "duration_fmt": "approx. {} h",
        "highlights_title": "Highlights",
        "map_title": "Map",
        "map_note": "Route line from OpenStreetMap — small deviations on the ground are possible. The MTB signposts on site are authoritative.",
        "bus_title": "Getting there by bus",
        "bus_intro": "Public transport is free in Luxembourg. These stops are on the route:",
        "bus_dist": "{} m from the route",
        "bus_lines": "Lines",
        "bus_no_lines": "see timetable",
        "bus_live": "Live departures for every stop: ian.lu/bus",
        "all_trails": "All tours",
        "filter_all": "All regions",
        "footer_note": "A project by ian.lu · Route data © OpenStreetMap contributors · Timetables: data.public.lu",
        "breadcrumb_home": "MTB Trails",
        "lang_switch_label": "Language",
        "card_cta": "View tour",
    },
}

UI = {
    "de": {
        "site_name": "Autopédestres Luxemburg",
        "index_title": "Autopédestres Luxemburg — alle Rundwanderwege mit Karte & Busanreise",
        "index_meta": "Die Autopédestre-Rundwanderwege in Luxemburg: interaktive Karte, Länge, Dauer, Schwierigkeit und Anreise mit dem kostenlosen Bus zu jedem Weg.",
        "index_h1": "Autopédestre-Rundwanderwege in Luxemburg",
        "index_intro": [
            "Die Autopédestres sind Luxemburgs klassische Rundwanderwege: über 100 lokale Schleifen im ganzen Land, dauerhaft mit dem blauen Symbol markiert und so angelegt, dass man immer wieder am Ausgangspunkt ankommt. Viele wurden vor Jahrzehnten für Ausflügler mit dem Auto geschaffen — daher der Name — aber heute erreicht man die meisten bequem mit dem Bus, denn der öffentliche Verkehr ist in ganz Luxemburg kostenlos.",
            "Diese Seite stellt die Wege einzeln vor — mit interaktiver Karte, Länge, ungefährer Gehzeit, Schwierigkeit und den Bushaltestellen direkt am Weg. Alle Streckendaten stammen aus OpenStreetMap, die Haltestellen aus den offiziellen Fahrplandaten Luxemburgs.",
        ],
        "trail_title": "{name} — Rundwanderweg {commune} | Autopédestres Luxemburg",
        "trail_meta": "{name}: {length} km Rundwanderweg bei {commune} ({region}). Karte, Gehzeit, Schwierigkeit und Anreise mit dem Bus.",
        "photo_alt": "Eindruck vom Wanderweg {name} bei {commune}",
        "nearby_title": "Wanderwege in der Nähe",
        "nearby_dist": "{d} km entfernt",
        "facts_title": "Auf einen Blick",
        "fact_length": "Länge",
        "fact_duration": "Gehzeit",
        "fact_difficulty": "Schwierigkeit",
        "fact_region": "Region",
        "fact_commune": "Gemeinde",
        "fact_type": "Typ",
        "fact_type_value": "Rundweg (Autopédestre)",
        "duration_fmt": "ca. {} Std.",
        "highlights_title": "Highlights",
        "map_title": "Karte",
        "map_note": "Streckenverlauf aus OpenStreetMap — kleine Abweichungen vor Ort sind möglich. Maßgeblich ist die blaue Markierung am Weg.",
        "bus_title": "Anreise mit dem Bus",
        "bus_intro": "Der öffentliche Verkehr ist in Luxemburg kostenlos. Diese Haltestellen liegen am Weg:",
        "bus_dist": "{} m vom Weg",
        "bus_lines": "Linien",
        "bus_no_lines": "siehe Fahrplan",
        "bus_live": "Live-Abfahrten für alle Haltestellen: ian.lu/bus",
        "all_trails": "Alle Wege",
        "filter_all": "Alle Regionen",
        "footer_note": "Ein Projekt von ian.lu · Streckendaten © OpenStreetMap-Mitwirkende · Fahrplandaten: data.public.lu",
        "breadcrumb_home": "Autopédestres",
        "lang_switch_label": "Sprache",
        "card_cta": "Zum Weg",
    },
    "fr": {
        "site_name": "Auto-Pédestres Luxembourg",
        "index_title": "Auto-Pédestres Luxembourg — toutes les boucles avec carte et accès en bus",
        "index_meta": "Les circuits Auto-Pédestre du Luxembourg : carte interactive, distance, durée, difficulté et accès en bus gratuit pour chaque boucle.",
        "index_h1": "Les circuits Auto-Pédestre du Luxembourg",
        "index_intro": [
            "Les Auto-Pédestres sont les boucles de randonnée classiques du Luxembourg : plus de 100 circuits locaux dans tout le pays, balisés en permanence du symbole bleu et conçus pour ramener toujours au point de départ. Beaucoup furent créés il y a des décennies pour les excursionnistes en voiture — d'où le nom — mais aujourd'hui la plupart s'atteignent facilement en bus, les transports publics étant gratuits dans tout le Luxembourg.",
            "Ce site présente les circuits un par un — avec carte interactive, distance, durée approximative, difficulté et les arrêts de bus situés directement sur le parcours. Les tracés proviennent d'OpenStreetMap, les arrêts des données horaires officielles du Luxembourg.",
        ],
        "trail_title": "{name} — boucle de randonnée à {commune} | Auto-Pédestres Luxembourg",
        "trail_meta": "{name} : boucle de {length} km près de {commune} ({region}). Carte, durée, difficulté et accès en bus.",
        "photo_alt": "Impression du sentier {name} près de {commune}",
        "nearby_title": "Sentiers à proximité",
        "nearby_dist": "à {d} km",
        "facts_title": "En bref",
        "fact_length": "Distance",
        "fact_duration": "Durée",
        "fact_difficulty": "Difficulté",
        "fact_region": "Région",
        "fact_commune": "Commune",
        "fact_type": "Type",
        "fact_type_value": "Boucle (Auto-Pédestre)",
        "duration_fmt": "env. {} h",
        "highlights_title": "Points forts",
        "map_title": "Carte",
        "map_note": "Tracé issu d'OpenStreetMap — de petits écarts sur le terrain sont possibles. Le balisage bleu sur place fait foi.",
        "bus_title": "Y aller en bus",
        "bus_intro": "Les transports publics sont gratuits au Luxembourg. Ces arrêts se trouvent sur le parcours :",
        "bus_dist": "à {} m du sentier",
        "bus_lines": "Lignes",
        "bus_no_lines": "voir horaires",
        "bus_live": "Départs en direct pour tous les arrêts : ian.lu/bus",
        "all_trails": "Tous les circuits",
        "filter_all": "Toutes les régions",
        "footer_note": "Un projet de ian.lu · Tracés © contributeurs OpenStreetMap · Horaires : data.public.lu",
        "breadcrumb_home": "Auto-Pédestres",
        "lang_switch_label": "Langue",
        "card_cta": "Voir le circuit",
    },
    "en": {
        "site_name": "Auto-Pédestres Luxembourg",
        "index_title": "Auto-Pédestres Luxembourg — every loop trail with map & bus access",
        "index_meta": "Luxembourg's Auto-Pédestre loop walks: interactive map, distance, duration, difficulty and free-bus access for every trail.",
        "index_h1": "Luxembourg's Auto-Pédestre loop trails",
        "index_intro": [
            "The Auto-Pédestres are Luxembourg's classic circular walks: more than 100 local loops across the country, permanently waymarked with the blue symbol and always bringing you back to where you started. Many were laid out decades ago for day-trippers arriving by car — hence the name — but today most are easy to reach by bus, since public transport is free throughout Luxembourg.",
            "This site presents the trails one by one — with an interactive map, distance, approximate walking time, difficulty and the bus stops right on the route. Route data comes from OpenStreetMap, stop data from Luxembourg's official timetable feed.",
        ],
        "trail_title": "{name} — loop walk in {commune} | Auto-Pédestres Luxembourg",
        "trail_meta": "{name}: {length} km loop walk near {commune} ({region}). Map, walking time, difficulty and how to get there by bus.",
        "photo_alt": "View from the {name} trail near {commune}",
        "nearby_title": "Trails nearby",
        "nearby_dist": "{d} km away",
        "facts_title": "At a glance",
        "fact_length": "Distance",
        "fact_duration": "Duration",
        "fact_difficulty": "Difficulty",
        "fact_region": "Region",
        "fact_commune": "Commune",
        "fact_type": "Type",
        "fact_type_value": "Loop (Auto-Pédestre)",
        "duration_fmt": "approx. {} h",
        "highlights_title": "Highlights",
        "map_title": "Map",
        "map_note": "Route line from OpenStreetMap — small deviations on the ground are possible. The blue waymarks on site are authoritative.",
        "bus_title": "Getting there by bus",
        "bus_intro": "Public transport is free in Luxembourg. These stops are on the route:",
        "bus_dist": "{} m from the trail",
        "bus_lines": "Lines",
        "bus_no_lines": "see timetable",
        "bus_live": "Live departures for every stop: ian.lu/bus",
        "all_trails": "All trails",
        "filter_all": "All regions",
        "footer_note": "A project by ian.lu · Route data © OpenStreetMap contributors · Timetables: data.public.lu",
        "breadcrumb_home": "Auto-Pédestres",
        "lang_switch_label": "Language",
        "card_cta": "View trail",
    },
}

UI_BY_CAT = {"hiking": UI, "mtb": UI_MTB}
