/* Luxembourg trail map — all Auto-Pédestres + MTB loops on one Leaflet map.
   Data comes from kaart/data/*.json, generated by scripts/trails/build_map.py. */
(function () {
  'use strict';

  var LUX_BOUNDS = [[49.44, 5.72], [50.19, 6.53]];
  var COLORS = { hiking: '#2e7d4f', mtb: '#d2691e' };
  var DIFFICULTIES = ['easy', 'moderate', 'hard'];
  var REGIONS = ['center', 'mullerthal', 'moselle', 'minett', 'eislek'];
  var MAX_KM = 40;

  var state = {
    lang: 'de',
    routes: [],
    geo: {},
    layers: {},          // slug -> L.Polyline
    cats: { hiking: true, mtb: true },
    difficulty: null,    // null = all
    region: null,
    maxKm: MAX_KM,
    busOnly: false,
    query: '',
    selected: null
  };

  var map, t, $;

  /* ---------------- helpers ---------------- */

  $ = function (sel) { return document.querySelector(sel); };

  /* Google encoded-polyline -> [[lat, lon], ...]. The build script packs the
     geometry this way because ian.lu is served without gzip. */
  function decodePolyline(str, precision) {
    var factor = Math.pow(10, precision || 5);
    var index = 0, lat = 0, lon = 0, points = [];

    while (index < str.length) {
      var shift = 0, result = 0, byte;
      do {
        byte = str.charCodeAt(index++) - 63;
        result |= (byte & 0x1f) << shift;
        shift += 5;
      } while (byte >= 0x20);
      lat += (result & 1) ? ~(result >> 1) : (result >> 1);

      shift = 0; result = 0;
      do {
        byte = str.charCodeAt(index++) - 63;
        result |= (byte & 0x1f) << shift;
        shift += 5;
      } while (byte >= 0x20);
      lon += (result & 1) ? ~(result >> 1) : (result >> 1);

      points.push([lat / factor, lon / factor]);
    }
    return points;
  }

  function detectLang() {
    try {
      var stored = localStorage.getItem('trails_lang');
      if (stored && window.MAP_I18N[stored]) return stored;
    } catch (e) { /* private mode */ }
    var nav = (navigator.language || 'en').slice(0, 2).toLowerCase();
    if (nav === 'lb' || nav === 'de') return 'de';
    if (nav === 'fr') return 'fr';
    return window.MAP_I18N[nav] ? nav : 'en';
  }

  function setLang(lang) {
    state.lang = lang;
    t = window.MAP_I18N[lang];
    try { localStorage.setItem('trails_lang', lang); } catch (e) { /* ignore */ }
    document.documentElement.lang = lang;
    renderChrome();
    renderList();
    if (state.selected) showDetail(state.selected);
  }

  function fmtKm(km) {
    var s = km.toFixed(1).replace(/\.0$/, '');
    return (state.lang === 'en' ? s : s.replace('.', ',')) + ' km';
  }

  function regionName(key) {
    var r = window.MAP_REGIONS[key];
    return r ? r[state.lang] : key;
  }

  /* Detail pages exist per language; routes.json stores the /de/ URL. */
  function pageUrl(route) {
    return route.url.replace('/de/', '/' + state.lang + '/');
  }

  function matches(route) {
    if (!state.cats[route.cat]) return false;
    if (state.difficulty && route.difficulty !== state.difficulty) return false;
    if (state.region && route.region !== state.region) return false;
    if (route.km > state.maxKm) return false;
    if (state.busOnly && !route.bus.some(function (b) { return b.on_route; })) return false;
    if (state.query) {
      var hay = (route.name + ' ' + route.place).toLowerCase();
      if (hay.indexOf(state.query) === -1) return false;
    }
    return true;
  }

  function visibleRoutes() { return state.routes.filter(matches); }

  /* ---------------- map ---------------- */

  function initMap() {
    map = L.map('map', { zoomControl: true, attributionControl: true })
           .fitBounds(LUX_BOUNDS);

    L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
      maxZoom: 18,
      attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'
    }).addTo(map);

    var Locate = L.Control.extend({
      options: { position: 'topleft' },
      onAdd: function () {
        var btn = L.DomUtil.create('button', 'locate-btn');
        btn.type = 'button';
        btn.textContent = '◎';
        btn.title = t.locate;
        L.DomEvent.on(btn, 'click', function (e) {
          L.DomEvent.stop(e);
          map.locate({ setView: true, maxZoom: 14 });
        });
        return btn;
      }
    });
    map.addControl(new Locate());
  }

  function drawRoutes() {
    state.routes.forEach(function (route) {
      var encoded = state.geo[route.cat] && state.geo[route.cat][route.slug];
      if (!encoded) return;
      var rings = encoded.map(function (ring) { return decodePolyline(ring); });
      var line = L.polyline(rings, {
        color: COLORS[route.cat],
        weight: 3,
        opacity: 0.85,
        smoothFactor: 1.4
      });
      line.on('click', function () { select(route.slug, false); });
      line.bindTooltip(route.name, { sticky: true, direction: 'top' });
      state.layers[route.slug] = line;
    });
    syncLayers();
  }

  /* Add/remove polylines so only matching routes are on the map. */
  function syncLayers() {
    var visible = {};
    visibleRoutes().forEach(function (r) { visible[r.slug] = true; });

    state.routes.forEach(function (route) {
      var line = state.layers[route.slug];
      if (!line) return;
      var shouldShow = !!visible[route.slug];
      var onMap = map.hasLayer(line);
      if (shouldShow && !onMap) line.addTo(map);
      else if (!shouldShow && onMap) map.removeLayer(line);
    });
  }

  function highlight(slug) {
    state.routes.forEach(function (route) {
      var line = state.layers[route.slug];
      if (!line) return;
      var isSel = route.slug === slug;
      line.setStyle({
        weight: isSel ? 6 : 3,
        opacity: !slug || isSel ? 0.9 : 0.35
      });
      if (isSel) line.bringToFront();
    });
  }

  function select(slug, fit) {
    state.selected = slug;
    highlight(slug);
    var line = state.layers[slug];
    if (line && fit !== false) map.fitBounds(line.getBounds(), { padding: [30, 30] });
    showDetail(slug);
    renderList();
  }

  function clearSelection() {
    state.selected = null;
    highlight(null);
    $('#detail').hidden = true;
    renderList();
  }

  /* ---------------- rendering ---------------- */

  function renderChrome() {
    $('#title').textContent = t.title;
    $('#subtitle').textContent = t.subtitle;
    document.title = t.title + ' · ian.lu';
    $('#search').placeholder = t.search;
    $('#cat-hiking .label').textContent = t.hiking;
    $('#cat-mtb .label').textContent = t.mtb;
    $('#filters-summary').textContent = t.filters;
    $('#lbl-difficulty').textContent = t.difficulty;
    $('#lbl-region').textContent = t.region;
    $('#lbl-length').textContent = t.maxLength + ': ' + state.maxKm + ' km';
    $('#lbl-bus').textContent = t.busOnly;
    $('#reset').textContent = t.reset;

    document.querySelectorAll('.langs button').forEach(function (b) {
      b.classList.toggle('on', b.dataset.lang === state.lang);
    });
    document.querySelectorAll('#f-difficulty .chip').forEach(function (c) {
      c.textContent = c.dataset.value ? t[c.dataset.value] : t.all;
    });
    document.querySelectorAll('#f-region .chip').forEach(function (c) {
      c.textContent = c.dataset.value ? regionName(c.dataset.value) : t.all;
    });
  }

  function renderList() {
    var routes = visibleRoutes();
    $('#count').firstChild.nodeValue = routes.length + ' ' + t.results + ' ';

    var list = $('#list');
    list.innerHTML = '';
    if (!routes.length) {
      var empty = document.createElement('p');
      empty.className = 'empty';
      empty.textContent = t.noResults;
      list.appendChild(empty);
      return;
    }

    routes.forEach(function (route) {
      var btn = document.createElement('button');
      btn.className = 'item' + (route.slug === state.selected ? ' on' : '');
      btn.type = 'button';

      var name = document.createElement('b');
      var dot = document.createElement('span');
      dot.className = 'swatch';
      dot.style.background = COLORS[route.cat];
      name.appendChild(dot);
      name.appendChild(document.createTextNode(route.name));

      var meta = document.createElement('span');
      meta.className = 'meta';
      meta.textContent = [
        fmtKm(route.km),
        route.gain + ' hm',
        t[route.difficulty],
        regionName(route.region)
      ].join(' · ');

      btn.appendChild(name);
      btn.appendChild(meta);
      btn.addEventListener('click', function () { select(route.slug); });
      list.appendChild(btn);
    });
  }

  function fact(label, value) {
    var box = document.createElement('div');
    box.className = 'fact';
    var b = document.createElement('b');
    b.textContent = value;
    box.appendChild(b);
    box.appendChild(document.createTextNode(label));
    return box;
  }

  function showDetail(slug) {
    var route = state.routes.filter(function (r) { return r.slug === slug; })[0];
    if (!route) return;

    var body = $('#detail-body');
    body.innerHTML = '';

    var h2 = document.createElement('h2');
    h2.textContent = route.name;
    body.appendChild(h2);

    var place = document.createElement('p');
    place.className = 'place';
    place.textContent = [route.place, regionName(route.region)].filter(Boolean).join(' · ');
    body.appendChild(place);

    if (route.photo) {
      var img = document.createElement('img');
      img.src = route.photo;
      img.alt = route.name;
      img.loading = 'lazy';
      body.appendChild(img);
    }

    var facts = document.createElement('div');
    facts.className = 'facts';
    facts.appendChild(fact(t.length, fmtKm(route.km)));
    facts.appendChild(fact(t.duration, route.duration + ' ' + t.hours));
    facts.appendChild(fact(t.gain, route.gain + ' m'));
    facts.appendChild(fact(t.difficulty, t[route.difficulty]));
    if (route.natural) facts.appendChild(fact(t.natural, route.natural + ' %'));
    body.appendChild(facts);

    if (route.pois && route.pois.length) {
      body.appendChild(headed(t.highlights, route.pois));
    }
    if (route.bus && route.bus.length) {
      body.appendChild(headed(t.bus, route.bus.map(function (b) {
        var lines = b.lines.length ? ' (' + b.lines.join(', ') + ')' : '';
        return b.name + lines + (b.on_route ? ' — ' + t.onRoute : '');
      })));
    }

    var actions = document.createElement('div');
    actions.className = 'actions';
    actions.appendChild(link(pageUrl(route), t.openPage, 'primary'));
    actions.appendChild(link(route.gpx, t.gpx, 'ghost'));
    body.appendChild(actions);

    $('#back').textContent = '‹ ' + t.backToList;
    $('#detail').hidden = false;
    $('#detail').scrollTop = 0;
  }

  function headed(title, items) {
    var frag = document.createDocumentFragment();
    var h3 = document.createElement('h3');
    h3.textContent = title;
    var ul = document.createElement('ul');
    items.forEach(function (text) {
      var li = document.createElement('li');
      li.textContent = text;
      ul.appendChild(li);
    });
    frag.appendChild(h3);
    frag.appendChild(ul);
    return frag;
  }

  function link(href, text, cls) {
    var a = document.createElement('a');
    a.href = href;
    a.className = cls;
    a.textContent = text;
    return a;
  }

  function refresh() {
    syncLayers();
    renderList();
  }

  /* ---------------- filter wiring ---------------- */

  function buildChips(container, values, labelFor, onPick) {
    var all = [null].concat(values);
    all.forEach(function (value) {
      var chip = document.createElement('button');
      chip.type = 'button';
      chip.className = 'chip';
      chip.dataset.value = value || '';
      chip.setAttribute('aria-pressed', value === null ? 'true' : 'false');
      chip.textContent = labelFor(value);
      chip.addEventListener('click', function () {
        container.querySelectorAll('.chip').forEach(function (c) {
          c.setAttribute('aria-pressed', c === chip ? 'true' : 'false');
        });
        onPick(value);
        refresh();
      });
      container.appendChild(chip);
    });
  }

  function wireControls() {
    document.querySelectorAll('.langs button').forEach(function (btn) {
      btn.addEventListener('click', function () { setLang(btn.dataset.lang); });
    });

    document.querySelectorAll('.cat').forEach(function (btn) {
      btn.addEventListener('click', function () {
        var cat = btn.dataset.cat;
        state.cats[cat] = !state.cats[cat];
        btn.setAttribute('aria-pressed', String(state.cats[cat]));
        refresh();
      });
    });

    $('#search').addEventListener('input', function (e) {
      state.query = e.target.value.trim().toLowerCase();
      refresh();
    });

    buildChips($('#f-difficulty'), DIFFICULTIES,
      function (v) { return v ? t[v] : t.all; },
      function (v) { state.difficulty = v; });

    buildChips($('#f-region'), REGIONS,
      function (v) { return v ? regionName(v) : t.all; },
      function (v) { state.region = v; });

    var slider = $('#f-length');
    slider.max = MAX_KM;
    slider.value = MAX_KM;
    slider.addEventListener('input', function (e) {
      state.maxKm = Number(e.target.value);
      $('#lbl-length').textContent = t.maxLength + ': ' + state.maxKm + ' km';
      refresh();
    });

    $('#f-bus').addEventListener('change', function (e) {
      state.busOnly = e.target.checked;
      refresh();
    });

    $('#reset').addEventListener('click', function () {
      state.difficulty = null;
      state.region = null;
      state.maxKm = MAX_KM;
      state.busOnly = false;
      state.query = '';
      $('#search').value = '';
      $('#f-bus').checked = false;
      slider.value = MAX_KM;
      $('#lbl-length').textContent = t.maxLength + ': ' + MAX_KM + ' km';
      document.querySelectorAll('.chips').forEach(function (group) {
        group.querySelectorAll('.chip').forEach(function (c, i) {
          c.setAttribute('aria-pressed', i === 0 ? 'true' : 'false');
        });
      });
      refresh();
    });

    $('#back').addEventListener('click', clearSelection);
  }

  /* ---------------- boot ---------------- */

  function fetchJson(url) {
    return fetch(url).then(function (res) {
      if (!res.ok) throw new Error(url + ' -> ' + res.status);
      return res.json();
    });
  }

  function boot() {
    t = window.MAP_I18N[detectLang()];
    state.lang = detectLang();

    initMap();
    wireControls();
    renderChrome();

    Promise.all([
      fetchJson('data/routes.json'),
      fetchJson('data/geo-hiking.json'),
      fetchJson('data/geo-mtb.json')
    ]).then(function (results) {
      state.routes = results[0].routes;
      state.geo.hiking = results[1];
      state.geo.mtb = results[2];
      drawRoutes();
      renderList();
      var el = $('#loading');
      if (el) el.remove();
    }).catch(function (err) {
      var el = $('#loading');
      if (el) el.textContent = t.error;
      if (window.console) console.error('[kaart]', err);
    });
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', boot);
  } else {
    boot();
  }
})();
