-- Generated by scripts/pro/build.py. Do not edit.

insert into public.pro_sites (
  slug, name, tagline, town, brand,
  hero, is_demo, sort_key
)
values (
  'demo-bistro',
  'Bistro du Marché',
  'Une table simple, des produits de saison',
  'L-1234 Luxembourg',
  '#7A2E2E',
  'demo-bistro/img/hero.webp',
  true,
  '0001'
)
on conflict (slug) do update set
  name = excluded.name,
  tagline = excluded.tagline,
  town = excluded.town,
  brand = excluded.brand,
  hero = excluded.hero,
  is_demo = excluded.is_demo,
  sort_key = excluded.sort_key,
  updated_at = now();

insert into public.pro_sites (
  slug, name, tagline, town, brand,
  hero, is_demo, sort_key
)
values (
  'brasserie-beaulieu',
  'Brasserie Beaulieu',
  'Brasserie et bar à vins à Bonnevoie',
  '25, rue Félix de Blochausen, L-1243 Luxemb' ||
  'ourg',
  '#2F4A3A',
  'brasserie-beaulieu/img/hero.webp',
  false,
  '0002'
)
on conflict (slug) do update set
  name = excluded.name,
  tagline = excluded.tagline,
  town = excluded.town,
  brand = excluded.brand,
  hero = excluded.hero,
  is_demo = excluded.is_demo,
  sort_key = excluded.sort_key,
  updated_at = now();

insert into public.pro_sites (
  slug, name, tagline, town, brand,
  hero, is_demo, sort_key
)
values (
  'cafe-de-la-gare',
  'Café de la Gare',
  'Café-restaurant en face de la gare de Muns' ||
  'bach',
  '197, rue Principale, L-5366 Munsbach, Schu' ||
  'ttrange',
  '#2F4A3A',
  'cafe-de-la-gare/img/hero.webp',
  false,
  '0003'
)
on conflict (slug) do update set
  name = excluded.name,
  tagline = excluded.tagline,
  town = excluded.town,
  brand = excluded.brand,
  hero = excluded.hero,
  is_demo = excluded.is_demo,
  sort_key = excluded.sort_key,
  updated_at = now();

insert into public.pro_sites (
  slug, name, tagline, town, brand,
  hero, is_demo, sort_key
)
values (
  'chocolats-du-coeur',
  'Chocolats du Coeur',
  'Chocolaterie artisanale du Tricentenaire',
  '14, Z.A.C. Klengbousbierg, L-7795 Bissen; ' ||
  'bar : 50, route de Diekirch, L-7220 Walfer' ||
  'dange',
  '#7A2E2E',
  'chocolats-du-coeur/img/hero.webp',
  false,
  '0004'
)
on conflict (slug) do update set
  name = excluded.name,
  tagline = excluded.tagline,
  town = excluded.town,
  brand = excluded.brand,
  hero = excluded.hero,
  is_demo = excluded.is_demo,
  sort_key = excluded.sort_key,
  updated_at = now();

insert into public.pro_sites (
  slug, name, tagline, town, brand,
  hero, is_demo, sort_key
)
values (
  'librairie-alinea',
  'Librairie Alinéa',
  'Librairie indépendante, rue des Capucins',
  '30, rue des Capucins, L-1313 Luxembourg',
  '#7A2E2E',
  'librairie-alinea/img/hero.webp',
  false,
  '0005'
)
on conflict (slug) do update set
  name = excluded.name,
  tagline = excluded.tagline,
  town = excluded.town,
  brand = excluded.brand,
  hero = excluded.hero,
  is_demo = excluded.is_demo,
  sort_key = excluded.sort_key,
  updated_at = now();

insert into public.pro_sites (
  slug, name, tagline, town, brand,
  hero, is_demo, sort_key
)
values (
  'lil-o-tresor',
  'Lil''O Trésor',
  'Vêtements pour enfants de 0 à 16 ans',
  '9, rue du Fossé, L-1536 Luxembourg',
  '#243A5E',
  'lil-o-tresor/img/hero.webp',
  false,
  '0006'
)
on conflict (slug) do update set
  name = excluded.name,
  tagline = excluded.tagline,
  town = excluded.town,
  brand = excluded.brand,
  hero = excluded.hero,
  is_demo = excluded.is_demo,
  sort_key = excluded.sort_key,
  updated_at = now();

insert into public.pro_sites (
  slug, name, tagline, town, brand,
  hero, is_demo, sort_key
)
values (
  'maison-viticole-roeder',
  'Maison Viticole Roeder',
  'Domaine viticole biologique à Steinheim',
  '27, rue de la Montagne, L-6586 Steinheim, ' ||
  'Rosport-Mompach',
  '#5A2A3E',
  'maison-viticole-roeder/img/hero.webp',
  false,
  '0007'
)
on conflict (slug) do update set
  name = excluded.name,
  tagline = excluded.tagline,
  town = excluded.town,
  brand = excluded.brand,
  hero = excluded.hero,
  is_demo = excluded.is_demo,
  sort_key = excluded.sort_key,
  updated_at = now();

insert into public.pro_sites (
  slug, name, tagline, town, brand,
  hero, is_demo, sort_key
)
values (
  'martins',
  'Martins',
  'Boulangerie-pâtisserie portugaise à Differ' ||
  'dange',
  '19, rue Émile Mark, L-4620 Differdange',
  '#8A5A22',
  'martins/img/hero.webp',
  false,
  '0008'
)
on conflict (slug) do update set
  name = excluded.name,
  tagline = excluded.tagline,
  town = excluded.town,
  brand = excluded.brand,
  hero = excluded.hero,
  is_demo = excluded.is_demo,
  sort_key = excluded.sort_key,
  updated_at = now();

insert into public.pro_sites (
  slug, name, tagline, town, brand,
  hero, is_demo, sort_key
)
values (
  'vis-a-vis',
  'Vis-à-Vis',
  'Bar-café au centre de Luxembourg',
  '2, rue Beaumont, L-1219 Luxembourg',
  '#6B4A2F',
  'vis-a-vis/img/hero.webp',
  false,
  '0009'
)
on conflict (slug) do update set
  name = excluded.name,
  tagline = excluded.tagline,
  town = excluded.town,
  brand = excluded.brand,
  hero = excluded.hero,
  is_demo = excluded.is_demo,
  sort_key = excluded.sort_key,
  updated_at = now();

delete from public.pro_sites
where slug <> all (array[
  'demo-bistro',
  'brasserie-beaulieu',
  'cafe-de-la-gare',
  'chocolats-du-coeur',
  'librairie-alinea',
  'lil-o-tresor',
  'maison-viticole-roeder',
  'martins',
  'vis-a-vis'
]);
